### ISSUE TITLE
Implementation of @chebfun/sum makes definite integrals involving fourtech fail

### ISSUE THREAD

**Issue by gradywright** [chebfun/chebfun#1004]
The `sum` command at the `chebfun` level allows users to specify an interval over which to compute the integral of a function `f`.  The way that this is implemented (in the case that the specified interval is not the domain of `f`) is to call `cumsum` on `f` then evaluate the difference between the result at the two ends of the interval.  This implementation causes problems when `f` is based on `fourtech` since `cumsum` at the `fourtech` level can only deal with cases where the mean of the function is zero (otherwise the resulting indefinite integral is not representable in the Fourier basis).  When the mean is not zero an error is thrown.

There is absolutely no reason the definite integral can't be computed when `f` is based on `fourtech`, it's just that the implementation does not allow for it.

One suggestion is to implement `integral` at the `tech` level that computes the definite integral over a given interval.  Another is to make `sum` at the `tech` level accept an optional interval (like `sum` at the `chebfun` level does), but this could potentially cause other issues.
A third is to have `cumsum` at the `fourtech` level return a 'fourfun' and a 'chebfun' and then evaluate both pieces, but this seems also difficult to deal with at the `chebfun` level since it involves a special case to check for.

**Comment by nickhale** [comment]
I think that in the `chebtech` case the argument for using the `cumsum()` approach rather than `restrict()` (i.e., `f{a,b}`) is that that former is faster as it only requires applying the cumsum recurrence relation = O(N), and then two point evaluations, also O(N) (and both with small implied constants). Conversely with `restrict()` we must evaluate at N points = O(N^2). This suggests we should push things down to the tech level and allow the tech to decide what it wants to do.

The argument for the `restrict()` approach would be that the implementation at the `chebfun` level would be somewhat simpler.
