### ISSUE TITLE
What is the vScale of a SINGFUN?

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#108]
The vScale off a CHEBTECH is the largest value contained in its .values field. SINGFUN simply borrows this as its own vScale.

However, the exponents in SINGFUN warp this value, and at the CHEBFUN level something this can therefore return something meaningless.

```
>> f = abs(x).^1.01
f = 
   chebfun column (2 smooth pieces)
       interval       length   endpoint values   exponents 
[      -1,       0]        1         1        0   0    1   
[       0,       1]        1         0        1   1    0   
Epslevel = 6.492624e-16.  Vscale = 5.000000e-01.  Total length = 2.
```

A user might expect the above to have a vScale approx = 1, but here it is a half. 

It's probably easy to come up with much more extreme examples.

**Comment by davidagross** [comment]
Hi everyone!  Long time no see.  

While I've been watching your work much less closely than I used to, the closure here did come across my inbox as a bit of a surprise.  Going back into #1026 we can see that vscales are still not the same for `f1`, `f2`, and `f3` as defined here:
```
>> f1 = chebfun(@(t) t.^0.5./exp(t), [0,inf], 'exps', [0.5 0])
>> f2 = chebfun(@(t) t.^0.5./exp(t), [0,1,inf], 'exps', [0.5 0 0 0])
>> f3 = f1; f3(1) = f3(1)
>> table([sum(f1); sum(f2); sum(f3)],[max(f1); max(f2); max(f3)],[f1.vscale;f2.vscale;f3.vscale],'VariableNames',{'sums','maxes','vscales'})

f1 =

   chebfun column (1 smooth piece)
       interval       length     endpoint values   endpoint exponents
[       0,     Inf]       44         0   -1e-15         [0.5      0]  
vertical scale = 2.7 


f2 =

   chebfun column (2 smooth pieces)
       interval       length     endpoint values   endpoint exponents
[       0,       1]       13         0     0.37         [0.5      0]  
[       1,     Inf]       61      0.37 -4.6e-16         [0      0]  
vertical scale = 0.71    Total length = 74


f3 =

   chebfun column (2 smooth pieces)
       interval       length     endpoint values   endpoint exponents
[       0,       1]       11         0     0.37         [0.5      0]  
[       1,     Inf]       60      0.37 -9.6e-16         [0      0]  
vertical scale = 0.71    Total length = 71


ans =

  3×3 table

          sums                 maxes               vscales     
    _________________    _________________    _________________

    0.886226925452756    0.428881942480354     2.73861278752584
    0.886226925452754    0.428881942480353    0.707106781186547
    0.886226925452759    0.428881942480349    0.707106781186632
```
While the sum (has been fixed and) is correct, the vertical scales are still quite off (by factors of almost 2 or 6 pretty much).

I'm just chiming in to make sure that this issue is still sufficiently tracked in, say, #1633 (even though a vscale discrepancy isn't actually documented there in this detail).

Thanks, and hope you all are doing well!
