### ISSUE TITLE
Singularity not detected; instead, result is identically zero nearly everywhere

### ISSUE THREAD

**Issue by hrothgar** [chebfun/chebfun#1301]
Construct the following chebfun:
```
>> fa = @(x) cos(1.5*acos(x)).^-1;
>> f = chebfun(fa, [-1 0], 'blowup', 2, 'splitting', 'on')
f =
   chebfun column (3 smooth pieces)
       interval       length   endpoint values  
[      -1,      -1]      126  -3.8e+07 -4.7e+05 
[      -1,      -1]       58  -4.7e+05 -4.7e+04 
[      -1,       0]        1         0        0 
Epslevel = 1.000000e-04.  Vscale = 5443746451065124.  Total length = 185.
```
The singularity was not detected, which is unfortunate. Worse, the chebfun is identically zero almost everywhere on its domain, and the jump between two of the pieces is on the order of 10^4. Here is the chebfun (blue) and the function from which it was constructed (red):
```
plot(f), ylim([-5 5])
xx = linspace(-1, 1, 1000);
hold on, plot(xx, fa(xx), 'r-')
```
![Chebfun plot](https://cloud.githubusercontent.com/assets/913747/5253262/3b9933be-799d-11e4-92a6-cc5cbe747f48.png)

If I pass correct exponents (`'exps', [-0.5 0]`) then the construction works fine. Also, if I construct with splitting _off_ then the singularity _is_ detected and the chebfun is happy (at length 64427, since the it doesn’t quite nail the exponent).

**Comment by aaustin141** [comment]
Since feature-prescribed-eps was merged (and, specifically, commit 6e02ae4a), I no longer notice this issue.  `singfun` still fails to pick up the singularity, but we no longer get that the result is identically zero nearly everywhere.  I'm going to mark this as closed.  If anyone else starts to see this behavior again, feel free to re-open or file another ticket.
