### ISSUE TITLE
trigfun gives wrong 'function not resolved' message

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1336]
Trigfun, quite properly for reasons of FFT efficiency, samples a function at 16, 32, 64, ... points, _not_ at 17, 33, 65.  But if convergence is not achieved, it says function not resolved using "65537" points (see below).  This seems to me misleading -- it will confuse a user who really wants to understand what is going on.  I realize that the number reported is actually maxLength, not the actual maximal grid size, but still I think it's confusing.  Should the largest power of 2 less than maxLength be reported, or...?  (See next issue for a further related confusion of mine).
```
Warning: Function not resolved using 65537 pts. Have you tried a
non-trig representation? 
> In chebfun.constructor>constructorNoSplit at 120
  In chebfun.constructor at 63
  In chebfun.chebfun>chebfun.chebfun at 221 
f =
   chebfun column (1 smooth piece)
       interval       length   endpoint values trig
[      -1,       1]    65536       1.5      1.5 
Epslevel = 1.572849e-12.  Vscale = 2.718282e+00.
```

**Comment by gradywright** [comment]
I tried fixing this by simply replacing the default 'maxLength' value to '2^16' in '@trigtech/techPref'.  This seems like the most natural thing to do.  Unfortunately it looks like 'chebfunpref' does not respect a given techs 'techPref' value for 'maxLength'.  It always uses whatever is defined in '@chebtech/techPref.m' for this value.  I'm hoping @aaustin141 can help me out with fixing this as he is the expert on prefs.  The branch I attempted to fix this on is `fix-trigTech-maxLength-and-resampling`.

**Comment by aaustin141** [comment]
The reason @gradywright's fix does not work is not because `chebfunpref` always uses the `chebtech` default value for `maxLength`.  It's because `chebfunpref` stores a default value for `maxLength` that is used by the upper layers, and that value happens to be `65537`.

To clarify, `maxLength` is one of the handful of preferences that are really properly tech preferences---techs need values for them in order to function properly---but which the upper layers  need to be able to control for various reasons (e.g., enabling automatic reduction of the maximum length of a `fun` when using breakpoint detection).  One of the assumptions made by the code in the upper layers is that any given `chebfunpref` object is always "complete" in the sense that it has values for all preferences that are controllable by the upper layers.  In particular, that includes these preferences like `maxLength` that apply to both layers.  The reason we make this assumption is so that we don't have to have a zillion checks all over the place that test to see if the desired preference is available in the supplied preference object and, if not, retrieve the default value.  Instead, all of that is managed by `chebfunpref`.

This means that `chebfunpref` somehow or another must ensure that the `maxLength` preference is available.  The way it currently does this is by storing a default value of `65537` for `maxLength`.  This is the value that gets used whenever you build a `chebfun` by calling the constructor unless you override it manually, i.e., it is as if the upper layers decided internally to set `maxLength` to this value.  At the bottom of the construction stack, all of the tech preferences that get set by the upper layers take priority when they get merged in with the tech defaults prior to tech construction.  So even if you set the default `maxLength` in `trigtech` to `65536`, it will get overridden by the default `65537` value during the construction process.  Currently, a tech's own default value for `maxLength` is only used if it is not supplied one by the upper layers, and at the moment, that only happens if you build the tech directly, i.e., by calling the `chebtech` or `trigtech` constructor.

I think this is suboptimal.  A tech's own default value for `maxLength` (and, indeed, those for all of the "abstract" tech preferences) _should_ be used by the upper layers as well.  For instance, if we have a tech that's really expensive to construct, default `maxLength` of 65537 might be too much.  It would be helpful if that tech could suggest something more reasonable.

The reason we don't do this at the moment is because implementing it gets messy.  The simplest and cleanest way I can think of at the moment would probably be via some trickery in `subsref` that gets these preferences "on-demand" from the tech set in the `tech` field if they don't have values already set, but this will be slow, both because of the extra processing in `subsref` and the fact that you need to create a tech object every time you want to do this.

An alternative would be to cache the tech defaults by asking for them once at `chebfunpref` construction and updating them whenever the `tech` field is changed via some trickery in `subsasgn`.  Unfortunately, this will have additional overhead of its own, as you will need to merge them in with the other preferences (or otherwise handle them specially) every time you do a preference access.  You can't merge them in at construction time or upon changes to the `tech` field because then they become indistinguishable from user-specified values, which means that making further changes to the `tech` field will either (a) result in the tech defaults being ignored or (b) true user-specified values being overridden, depending on how you choose to handle it.

**Comment by gradywright** [comment]
Thanks for the explanation.  Is it possible for `chebfunpref` to accept an optional input argument of the `tech` that should be used.  Then if a preference field is not specified upon construction, it simply sets the the `techPrefs` fields to the values found in `tech.techPrefs`?  It seems odd to me that in the `chebfun` constructor we deal with getting all the preferences independently of whether the user specifies the `trig` flag.  It is only after preferences are all determined that we then override `pref.tech`, setting it to `trigtech`, but do nothing to the fields in `pref.techPrefs`.  If I understand the code correctly, it appears that other fields like `eps`, `fixedLength`, `extrapolate`, and `sampleTest` will also not be set to the values specified in `<techtype>.techPref`.
