### ISSUE TITLE
Unexpected behaviour from @SINGFUN/CHEBCOEFFS().

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1358]
`@singfun/chebcoeffs()` does not return the correct coefficients:

```
n = 14;

x = chebfun('x');
f1 = sqrt(1+x).*exp(x);
c1 = chebcoeffs(f1, n);

f2 = chebfun(@(x) sqrt(1+x).*exp(x), 1000);
c2 = chebcoeffs(f2, n);

f3 = chebfun(@(x) sqrt(1+x).*exp(x), 'trunc', n);
c3 = chebcoeffs(f3, n);

[c1 c2 c3]
```
```
ans =
    2.2992    1.4638    1.4638
    2.3195    1.7951    1.7951
    0.8176    0.4702    0.4702
    0.1380    0.1064    0.1064
    0.0203    0.0037    0.0037
    0.0031    0.0073    0.0073
   -0.0011   -0.0042   -0.0042
    0.0014    0.0032    0.0032
   -0.0013   -0.0025   -0.0025
    0.0012    0.0020    0.0020
   -0.0012   -0.0016   -0.0016
    0.0011    0.0013    0.0013
   -0.0011   -0.0011   -0.0011
    0.0005    0.0010    0.0010
```

I first suspected that it was simply returning the coefficients of `exp(x)`, but that's not the case either.

An additional problem is that if no `N` is given to `chebcoeffs()` then the length of the **smoothPart** of the function is given to 'singfun/chebcoeffs', even though the function will typically have a non-compactly supported Chebyshev expansion. Here's an extreme case:
```
>> chebcoeffs(sqrt(1+x))
ans =
    1.4142
```

I suggest that perhaps `chebcoeffs()` should **always** require an `N` to be passed, otherwise we're expecting the user to know too much about the underlying representation.

**Comment by kuanxu** [comment]
First, just want to check if we are on the same page, since c1 I have is a row column (this perhaps is another bug?):

```
n = 14;

x = chebfun('x');
f1 = sqrt(1+x).*exp(x);
c1 = chebcoeffs(f1, n);

ff = sqrt(1+x);
cf = chebcoeffs(ff, n).';

gg = exp(x);
cg = chebcoeffs(gg, n);

f2 = chebfun(@(x) sqrt(1+x).*exp(x), 1000);
c2 = chebcoeffs(f2, n);

f3 = chebfun(@(x) sqrt(1+x).*exp(x), 'trunc', n);
c3 = chebcoeffs(f3, n);

[c1.' c2 c3]
```
```
ans =

   2.299240328220939   1.463845823486334   1.463845891599060
   2.319529615157925   1.795053891466603   1.795053755241081
   0.817640239549256   0.470222165451576   0.470222301677309
   0.138010266952859   0.106358108356084   0.106357972129999
   0.020327992445620   0.003745239624069   0.003745375850645
   0.003111366548543   0.007336789874026   0.007336653646816
  -0.001133372051422  -0.004154261959791  -0.004154125731808
   0.001367740399580   0.003210042146694   0.003209905917797
  -0.001292098323060  -0.002480718946448  -0.002480582716495
   0.001217681315022   0.001977627379659   0.001977491148510
  -0.001151532210993  -0.001611894251292  -0.001611758018806
   0.001102625628663   0.001338370552791   0.001338234318827
  -0.001073049737234  -0.001128623398639  -0.001128487163055
   0.000531593984582   0.000964357080178   0.000964220842834
```

Second, the reason why the coeffs of f1 are not those of `exp(x)`'s is that those coefficients are computed by inner product of the whole function (singPart*smoothPart) with the Chebyshev weight (see Line 33 of @singfun/chebcoeffs). You wrote that algorithms, I guess?

**Comment by nickhale** [comment]
Yes, the fact that c1 is a row (in your version) is a bug. I fixed that fix-singfun-chebcoeffs.

I don't expect it to return the coefficients of `exp(x)`, I expect it to return the coefficients of `sqrt(1+x).*exp(x)`. Currently it does neither. I think I found the problem(s):
 1) The 2/pi scaling was not being included in singfun
 2) There were some flipud issues, probably relating to when the coefficient ordering got changed.

So the first issue should be fixed (in fix-singfun-chebcoeffs).

This is still a problem though:

```
>> chebcoeffs(sqrt(1+x))
ans =
    0.9003
```

**Comment by aaustin141** [comment]
Reopening this, since #1359 only fixed this in part.

**Comment by nickhale** [comment]
@aaustin141 - do you have any thoughts on the proposed solution to the second part of the problem?

**Comment by aaustin141** [comment]
I haven't thought about this carefully---so forgive me if what I'm saying is nonsense---but it seems to me that the problem is that the default number of coefficients to request is being set by `chebfun` to be `length(f)`.  Is there a reason it needs to do that?  In the single-fun case (which is the only one where this matters, since otherwise, we have to work at the `chebfun` level and do the integrals), could we not just call `chebcoeffs(f.funs{1})` (no `n` input) and let the lower layers decide how many coefficients to return?  If such a call reaches `chebtech`, it'll return the stored coefficients, but if it hits `singfun` or `trigtech`, we'll get an error asking the user to specify `n`.

Would something like this work?

**Comment by nickhale** [comment]
That would work, but then problem is that piecewise functions are treated differently from smooth ones. Now, I know that happens in a bunch of places, but here it doesn't seem necessary. Is `chebcoeffs(f)` often used (i.e., without a given `n`)? I feel always demanding `chebcoeffs(f, n)' would be cleaner.
