### ISSUE TITLE
bug in `doublelength`

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1410]
`doublelength` seems to be producing results that are too big by 2, in both standard and trig mode.  Thus for example:
```
>> length(chebfun('x','doublelength'))
ans =  5
>> length(chebfun('sin(pi*x)','trig','doublelength'))
ans = 7
```
The results here should be 3 and 5.  I'm a little puzzled how this slipped by us... am I missing something?

I am taking the liberty of assigning this hopefully very minor fix to @hrothgar, since he's been involved in `doublelength` already and, more to the point, I encountered this problem when writing an Example to illustrate `doublelength`, which I have just sent to @hrothgar to install when the moment is right.

BTW I also didn't spot any documentation of `doublength` (which presumably should appear in the `help chebfun` text), but the bug is the main thing here.

**Comment by hrothgar** [comment]
Doublelength creates a chebfun of length 2\*N+1, where N is the length the constructor would normally choose. Since `chebfun('x')` is of length 2, `chebfun('x','doublelength')` creates a chebfun of length 2\*2+1 = 5. And since the trig representation of sin(pi\*x) is of length 3, the doublelength version is of length 2\*3+1 = 7.

(The reason we did 2*N+1 was to maintain odd degree in the trig representations. The reason we haven't created separate rules for trig and Chebyshev representations is that it would be too much work.)

Do you think the rule should be changed to 2*N–1?

Thanks for pointing out the missing documentation. I'll take care of that.

**Comment by trefethen** [comment]
Yes, it should certainly be changed to 2N-1!  Doubling the degree
makes sense.  Doubling degree-plus-1 makes no sense that I can see.
If you read the text of my Example you'll see what I mean.

      Nick


On 23/02/15 09:48, Hrothgar wrote:
> Doublelength creates a chebfun of length 2\*N+1, where N is the length the constructor would normally choose. Since `chebfun('x')` is of length 2, `chebfun('x','doublelength')` creates a chebfun of length 2\*2+1 = 5. And since the trig representation of sin(pi\*x) is of length 3, the doublelength version is of length 2\*3+1 = 7.
>
> (The reason we did 2*N+1 was to maintain odd degree in the trig representations. The reason we haven't created separate rules for trig and Chebyshev representations is that it would be too much work.)
>
> Do you think the rule should be changed to 2*N–1?
>
> Thanks for pointing out the missing documentation. I'll take care of that.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/chebfun/chebfun/issues/1410#issuecomment-75513842

-- 
L. N. Trefethen FRS
Professor of Numerical Analysis and Fellow of Balliol College, Oxford University
Global Distinguished Professor, New York University
Postal address: Oxford Maths Inst, Woodstock Rd, Oxford OX2 6GG, UK
people.maths.ox.ac.uk/trefethen, (+44) 1865 615317
