### ISSUE TITLE
enabling `V'*V` when `V` is a chebmatrix of quasimatrix style

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1451]
In drafting a chapter of the ODE book I wanted to show that eigenfunctions of self-adjoint differential operators are orthogonal.  I tried
```
L = chebop(@(t,y) diff(y,2),[-pi pi],'dirichlet');
[V,D] = eigs(L);
C = V'*V
```
This doesn't work.  More precisely, it does work, but the output is a 6x6 chebmatrix whose entries are scalars.  This of course is crazy from a user point the view; the user would expect to get a 6x6 matrix.

I've been talking with @asgeirbirkis, and we propose the following, though at a later date more cosmic changes might be considered as chebmatrix technology evolves.  We propose that for the moment, the operation
```
A*B
``` 
between chebmatrices A and B with appropriately oriented rows/columns on appropriate domains should be implemented in such a way as to produce the appropriate matrix as output.

Minor note along the way: the help text of `chebop/eigs` currently says that V will be a quasimatrix, not a chebmatrix.  This help text needs to be fixed. 

@asgeirbirkis has very kindly agreed to take a look at this if nobody objects to the idea.

**Comment by asgeirbirkis** [comment]
As a backstory for the solution that @trefethen and I propose (and so that our trains of thought get archived), here's my take on the problem on the potential solutions. First of all, there are a few issues going on with the current implementation which leads to the undesired behaviour:

* The reason why we return chebmatrices, rather than quasimatrices from eigs is that for coupled systems, that's the only way to stack them nicely. For example,

```
A = chebop(@(x, u, v) [-u + diff(v) ; diff(u)], d);
A.lbc = @(u, v) u;
A.rbc = @(u, v) u;
[V, D] = eigs(A, 5)
V =
  2 x 5 chebmatrix of block types:
   'chebfun'    'chebfun'    'chebfun'    'chebfun'    'chebfun'
   'chebfun'    'chebfun'    'chebfun'    'chebfun'    'chebfun'
```
At some point, we decided that chebmatrices could only contain single column chebfuns, not array valued/quasimatrices, as otherwise, things would get way too messy.

* The system will automatically enforce this behaviour, e.g.
```
>> T = chebpoly(1:4); % Array valued chebfun
>> TT = [T; T]
TT =
  2 x 4 chebmatrix of block types:
   'chebfun'    'chebfun'    'chebfun'    'chebfun'
   'chebfun'    'chebfun'    'chebfun'    'chebfun'
```

* For the `V'*V` operation of a chebmatrix, I think that when the result only consists of doubles, it'd be reasonable to return a normal numerical matrix, rather than a chebmatrix. This is for example the output we get for `V'*V` when `V` is a array-valued chebfun/quasimatrix, the inputs are two `chebfun` objects, but the output is a standard Matlab matrix.

* It'd be possible to get the desired behaviour with `V = chebfun(V); C = V'*V`, However, that's neither a nice nor intuitive syntax.

There were few approaches we discussed:

1. In the scalar case (i.e. when only one unknown function appears in the list of arguments to the operator), we return an array valued chebfun rather than quasimatrix. This is a one line fix, however, it'll make the scalar and system cases inconsistent, so @trefethen and I were not a fan of this solution.

2. We continue to return chebmatrices, but fix the V'*V operation to give a meaningful output. This is the solution that this issue proposes.

3. We allow chebmatrices to store quasimatrices/array valued chebfuns, and for systems, return a chebmatrix of vertically stacked quasimatrices. This is a pretty major change which needs careful thinking about, and might have further consequences down the road as the chebmatrix class gets more complicated. For those reasons, we decided against this solution (at least for now).

**Comment by trefethen** [comment]
Yes, I agree.  Thanks @asgeirbirkis.

**Comment by asgeirbirkis** [comment]
Once #1454 gets merged, the output from the example above is as follows:
```
L = chebop(@(t,y) diff(y,2),[-pi pi],'dirichlet');
[V,D] = eigs(L);
C = V'*V
C =
    1.0000    0.0000   -0.0000   -0.0000   -0.0000   -0.0000
    0.0000    1.0000   -0.0000   -0.0000    0.0000   -0.0000
   -0.0000   -0.0000    1.0000   -0.0000   -0.0000    0.0000
   -0.0000   -0.0000   -0.0000    1.0000    0.0000    0.0000
   -0.0000    0.0000   -0.0000    0.0000    1.0000   -0.0000
   -0.0000   -0.0000    0.0000    0.0000   -0.0000    1.0000
```
