### ISSUE TITLE
Should the periodic flag give an error when given an even number of samples?

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1460]
So, I just found out that trigtech only works with odd length samples. Fine, I understand that parity is annoying here.  But, I do not get an error if I try: 
```
f = chebfun( ones(32,1), 'periodic'  );
g = cumsum(f);
```
Now, `g` is the zero function! I was expecting an error or for it to be cast to a chebfun (with a warning?).

**Comment by gradywright** [comment]
trigtechs should work completely fine for even length samples.  Is there somewhere in the trigtech code that would lead you to believe otherwise @ajt60gaibb?

The bug you found is a bug with @chebfun/cumsum.  It is incorrectly checking the mean of an even length trigfun (another bug from when we switched the order of the coefficients).  I will have a fix (and test) soon.

**Comment by ajt60gaibb** [comment]
Oh, `trigtech/cumsum` made me think that because of the way it was checking the coefficients.

**Comment by ajt60gaibb** [comment]
Also, everytime I tried to make a `trigfun` from a function handle it came out with an odd number of coefficients. This seems to happen also when an even number would do.

**Comment by ajt60gaibb** [comment]
Also, things like this: 
```
f = trigtech(@(x) exp(1i*pi*x) + exp(-2i*pi*x)); 
f.coeffs
ans =

   1.0000 - 0.0000i
  -0.0000 - 0.0000i
   0.0000 + 0.0000i
   1.0000 - 0.0000i
   0.0000 - 0.0000i
```

**Comment by gradywright** [comment]
Unless you explicitly construct from samples, a `trigfun` will always be odd.  I'm pretty sure more people than just me know this and that we decided this would be fine since even length trigfuns are odd (pun-intended)--they break symmetry between numbers of cosine/sine modes.   Do others have comments?

**Comment by trefethen** [comment]
About even vs odd, yes, trigfuns are supposed to have odd length unless you explicitly force it to be even.  This is discussed carefully in our paper on the subject, `https://people.maths.ox.ac.uk/trefethen/trigpaper.pdf`; see in particular remark 3 on p. 2 and the text on p. 10.  Speaking philosophically, let me comment that whereas of course in principle everything about even vs. odd trigonometric expressions is utterly elementary, in practice this is tricky subtle stuff and our paper is possibly the only place on earth that really discusses it carefully -- ultimately because Chebfun in unusual in being forced to confront such matters.

**Comment by mhsnjvd** [comment]
If I may also add, trigonometric interpolation at even number of points
only makes sense for the special case of equally spaced points. The
interpolation problem has non-unique solutions for arbitrary even
interpolation points. See the last paragraph at p.4 of our paper
http://zindajaved.com/html/publications/javedTrefethen2015.pdf for a
trivial example of non-uniqueness.

**Comment by aaustin141** [comment]
The issue that was originally posted here has been addressed.  Shall we close this ticket?
