### ISSUE TITLE
Solving a time-dependent differential equation utilizing the Crank-Nicolson-Methode

### ISSUE THREAD

**Issue by ErashMuhs** [chebfun/chebfun#1463]
Dear programmers,

I am trying since a little while to solve a time dependent differential equation with high accuracy utilizing the chebfun-functions for the spatial-discretization and some of the well known algorithms for the time-discretization (like Dupont-II, Crank-Nicolson, Adam Bashfort, Adams Moulton, Euler-Backward/Forward, Runge Kutta...). The solution shows the diffusion of specific particles into an empty region. The approach is probably similar to the pde15s-function.

To simplify the problem, I used the Crank-Nicolson-Methode and show just the first timestep in the following. The code is working so far.

``` matlab
clear;
%x domain
xdom=domain(-0.5,0.5);
x=chebfun('x',xdom,'splitting','on');
tmax=1; dt=0.01;

D=@(u) sqrt(u);
dD=@(u) 1./(2*sqrt(u)); %solved by hand ---> better would be: diff(D(u)) but which is not working; 
G=@(u) D(u).*diff(u,2)+dD(u).*diff(u,1).^2;

%Initial distribution in x
InitialDistribution=0.001+0.*x;  %0.*x;%  ---> better would be: 0 but which is not working

%LHS and RHS of the operator utilizing the Crank-Nicolson-Methode
%LHS Problem
LHS=chebop(xdom);
LHS.op=@(u) u-dt/2*G(u);
LHS.init=1;
LHS.lbc=1;
LHS.rbc=1;

%RHS Problem
RHS=@(u) u+dt/2*G(u);

%Preferences for the solve of the differential equation
options = cheboppref();
options.display = 'iter';
options.errTol = 1e-6;
options.discretization = @ultraS;

%Solve the differential equation
NextTimeStep=solvebvp(LHS,RHS(InitialDistribution),options);
%plot the result
plot(NextTimeStep)
```

My questions are the following:
**-1-** The function dD represents the analytically calculated derivative of the function D. By replacing dD with diff(D(u)), the program is not working anymore, even if dD is calculated correctly.

**-2-** The initial contribution InitialDistribution=0 leads to an error which might be clear due to the 1/sqrt(u) - part in dD. To avoid that error, the initial value is set to 0.001. However, by further lowering it to 0.0001, the following warning I have seen over and over again during the last days appears:

> Warning: Non-integer difference in the exponents of the two SINGFUN objects: The result may not >be accurate. 
> In singfun.plus at 125
>  In classicfun.plus at 37
>  In chebfun.plus at 107
>  In chebmatrix.plus at 58
>  In chebmatrix.minus at 7
>  In chebop.solvebvpNonlinear at 208
>  In chebop.solvebvp at 208
>  In Test11Problem at 32 

After a couple of those warnings, the program crashs. Is there a way around?

**-3-** I am trying to implement an explicit solving algorithms as for example the Euler-Forward-Method. Is there a way to implement boundary conditions without inverting a matrix? In such a case, the LHS=1 and the equation simplifies to:

```
NextTimeStep=RHS(InitialDistribution);
```

The RHS seems to be determined. However, the usual matrix-algorithm when numerically solving the equation provides the opportunity to fix the boundaries. Maybe a similar way exist for chebfuns?! Just fixing the ends of the interval after every timestep also leads to a crash of the program.

If someone has any solution or suggestion for one of those problems, I would be very glad to here from you! I am struggeling since a little while now and couldn't find any solutions so far.

Best regards,

Gregor

**Comment by nickhale** [comment]
Problems 1 & 2 are related, and mainly caused by the `sqrt(u)` term. When the `chebfun/sqrt()` methods is given a function with a root, it will try and introduce a breakpoint there (as it is likely the result will be singular.) It will also probably introduce `'exponents'` to try and resolve this singularity. Compare the following:
```
>> x = chebfun('x');
>> sqrt(x.^2)
ans =
   chebfun column (2 smooth pieces)
       interval       length     endpoint values exponents
[      -1,-1.7e-16]        2         1        0 
[-1.7e-16,       1]        2         0        1 
epslevel = 1.332268e-15   vscale = 1   Total length = 4
>> sqrt(x.^2+.001)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]      781         1        1 
epslevel = 2.842171e-14   vscale = 1.000500e+00
>> sqrt(x.^2-.001)
ans =
   chebfun column (3 smooth pieces)
       interval       length     endpoint values   endpoint exponents
[      -1,  -0.032]       60         1        0         [0      0.5]  
[  -0.032,   0.032]        1    complex values         [0.5      0.5]  
[   0.032,       1]       60         0        1         [0.5      0]  
epslevel = 9.936076e-14   vscale = 9.994999e-01   Total length = 121
```
We see that deal with the sqrt is, in some sense, unstable as a small perturbation (raising the input up or down a little) can alter the way the result is represented. 

Since there's nothing to prevent the solution `u` in your example being negative, there's nothing to stop break points and exponents being introduced as in the final case above. The `chebop` system is not designed to deal with exponents, which is probably why is crashes.

I should note that `pde15s()` works quite differently in that most of the RHS is dealt with discretely, and this is just piped to `ode15s()`. This is mostly for speed. Trying to do this time-stepping in continuous mode with chebfuns usually turns out to be pretty slow. 

I don't have any suggestions for the boundary conditions in the explicit case.
