### ISSUE TITLE
sum(), integral() and roots()

### ISSUE THREAD

**Issue by thorstendahmen** [chebfun/chebfun#1470]
One of the most distinctive sentences, which I associate with Chebfun is the following which I quote from the top of the Chebfun homepage:

"Most Chebfun commands are overloads of familiar MATLAB commands — for example `sum(f)` computes an integral,[...]"

But does this really make sense? For me `sum()` is an operator that takes a _variable_ number of inputs and the output is the sum of these inputs. Thus, if the input is only one function, then I would expect that the output is the sum of this function, i.e. trivially just the same function and not the integral. What is actually the purpose of using sum instead of integral? Isn't it just another name?

Besides, I would expect that `integral()` takes three arguments, not only one. One for the integrand and two for the left and right limits.

Furthermore, I don't like the syntax `N.bc = @(x,u) sum(x+u)`. Neglecting the points above, wouldn't `N.bc = @(u) sum(@(x) x+u(x))` be more appropriate? I.e. should an integrand not generally be given as an anonymous function with the independent variable being the argument. I think the whole operator defining the boundary condition should only be a function of `u`, independent of `x`.

And to complete the initial sentence from the Webpage:
"[...] `roots(f)` finds zeros, and `u = L\f` solves a differential equation."
Why, then, does `u = roots(L-f)` not find the roots of the operator `L-f`, giving a result identical to `u = L/f`?

**Comment by asgeirbirkis** [comment]
Hi Thorsten,

Just wanted to give you my views (and not necessarily the "official Chebfun team view").

1. The chebfun `sum` can be thought of as the continuous limit of the summation of elements of vector. There is also an `chebfun/integral` method, which has the same functionality as `sum`. That method was introduced because we recognized that `integral` might come more intuitively to some users, also, it's in accordance with fairly recently introduced `integral` methods of standard Matlab (which previously were always called `quad...`). It's possible to pass both `sum` and `integral` methods limits, but by default, the integral over the whole domain of the function gets computed. I'm not sure that I agree with your thinking about `sum` is to return the sum of variable number of inputs, to me, that's more simply like `plus`.

2. There are both technical and aesthetic reasons for the way we impose `N.bc`, `N.bc = @(x,u) sum(x+u).` leads to simpler code, and to my eyes at least, looks nicer than `N.bc = @(u) sum(@(x) x+u(x))`.

3. Regarding `u=L\f` rather than `u = roots(L-f)`, there are again a few reasons. One being that \ overloads the familiar Matlab syntax for solving linear systems of equations. For `Ax = b`, it'd look weird to me to solve for `x` via `x = roots(A-b)`. Also, what kind of operator do you think of `L-f` to be, `L` has dimensions `inf x inf` while `f` has dimensions `inf x 1`, so what kind of mathematical object should `L-f` be?

**Comment by thorstendahmen** [comment]
Hi Asgeir,
thanks for your answer!
1.) Ok, so I am and integral-user from now ;). It is funny that I had been thinking for years that the sum-overload is like a textbook example for object-oriented programming. But now as I have really thought about it for the first time it became clear that it is not at all. That's embarrassing for a computer scientist like me ;).
2.) For sure I agree that it looks nicer and I can imagine that upto now there might have been some technical advantage. But for the extension I am currently working on this is a pain, at least as long as you are stupid like me and don't realize that mathematically N.bc it is not a function of x for several days. Well, for now I know what to do. We may discuss this further when I am finished with what I am doing. Thus, I may assume that in Chebfun technical and aesthetic aspects are sometimes more important than strict mathematical correctness ;)?
3.) The objects I am working with represent affine operators and L-f would be of that type. (Sorry, I forgot that Chebfun uses linear operators when I wrote that question). In my code I am using roots and affine operators for technical reasons internally and \ is just a wrapper function for aesthetic reasons ;).
Thanks for the discussion!

**Comment by jrus** [comment]
You have to think about it as mirroring as closely as possible the semantics of Matlab, rather than the semantics of some other language or mathematical language more generally. In the context of Matlab, pretty much all the choices the Chebfun team made are quite sensible. Coming from another environment, some of them cause some head scratching though, to be sure.
