### ISSUE TITLE
bug: failure of `chebfun(tan(x))`

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1486]
Something very basic is going wrong here!
```
>> f = chebfun(@(x) tan(x),[0 pi],'splitting','on','blowup','on')
f =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[       0,     3.1]        1       -64      -64 
epslevel = 2.848295e-01   vscale = 6.365674e+01
```

**Comment by nickhale** [comment]
This is a essentially a problem of vertical scales. The `chebfun` constructor tries to construct relative to a vertical scale, but what does this mean for a function which is unbounded? (See #108.) To perform this relative construction, the constructor keeps track of **the maximum of all sampled values (with the exception of inf *)** during the *entire* construction process. 

The reason the example above returns such a crazy result is that, during the first stage of construction, the constructor samples at `x = pi/2`, and in MATLAB
```
>> tan(pi/2)
ans =
     1.633123935319537e+16
```
Now, is this were `inf`, it wouldn't be included in the vscale. However, since it's finite, it *is* and the constructor now attempts to construct a chebfun relative to a vscale of 10^16.

In the short term, this can be easily fixed by only allowing contributions to the global vscale which come from `happy` `fun`s. (I have an upcoming pull request which implements this in which all tests seems to pass.) However, I'm no entirely convinced this is the right thing to do.

In the long term, this seems to be another indication that the role of `vscale` needs some reconsideration, almost as much as `epslevel`.

**Comment by nickhale** [comment]
This is also a problem. 
```
>> f=chebfun(@(x) tan(x),[5*pi,6.5*pi],'splitting','on','blowup',1)
f =
   chebfun column (7 smooth pieces)
       interval       length     endpoint values   endpoint exponents
[      16,      17]       21  -1.1e-14      Inf         [0      -1]  
[      17,      17]        1  -2.6e+12 -2.6e+12         [0      0]  
[      17,      17]       30  -1.2e+12 -1.3e+10         [0      0]  
[      17,      17]       62  -1.3e+10 -1.3e+08         [0      0]  
[      17,      17]      117  -1.3e+08 -1.3e+06         [0      0]  
[      17,      17]      121  -1.3e+06 -1.3e+04         [0      0]  
[      17,      20]        1         0        0         [0      0]  
epslevel = 1.000000e-04   vscale = 1.020058e+15   Total length = 353
```

I will push a fix to the same branch.

**Comment by nickhale** [comment]
et voilà
```
>> f = chebfun(@(x) tan(x),[5*pi,6.5*pi],'splitting','on','blowup',1)
f =
   chebfun column (2 smooth pieces)
       interval       length     endpoint values   endpoint exponents
[      16,      17]       27  -1.1e-14      Inf         [0      -1]  
[      17,      20]       18      -Inf      Inf         [-1      -1]  
epslevel = 1.000000e-14   vscale = 1.020058e+15   Total length = 45
```
