### ISSUE TITLE
Squaring mixed partial derivatives that should be 0

### ISSUE THREAD

**Issue by awsimpson** [chebfun/chebfun#1536]
I've encountered a problem with squaring a vanishing mixed partial derivative. For example,

```
>> w = chebfun2(@(x,y) x.^2+y.^2);
>> diffx(diffy(w)).^2
```

does not run. Can anyone provide a solution or a practical work-around?

**Comment by aaustin141** [comment]
It looks to me like what's happening here is that the squaring operation invokes the `chebfun2` constructor, which has trouble resolving things because of noise that arises when evaluating the (almost exactly zero) `chebfun2` for `diffx(diffy(w))`.  @ajt60gaibb:  is there anything we can do about this?

**Comment by ajt60gaibb** [comment]
This is just embarrassing, though it is to do with the fact that `diff` loses a digit of accuracy and that `w_{xy}` is zero.  Thus, the Chebfun2 constructor tries to resolve it to 16 relative digits when only 16 absolute digits is possible.    

I believe we need to change `chebfun2/power()` a little. 

Here is an embarrassing workaround for now, but this is not how one should use Chebfun2: 

```
w = chebfun2(@(x,y) x.^2+y.^2);
[xx, yy] = meshgrid( chebpts(10) ); 
f = chebfun2( feval(diffx(diffy(w)),xx,yy).^2 );
plot(f)
```

**Comment by ajt60gaibb** [comment]
This now works.   
```
w = chebfun2(@(x,y) x.^2+y.^2);
diffx(diffy(w)).^2
```
