### ISSUE TITLE
Tolerance issue in Chebfun2 rank-determination

### ISSUE THREAD

**Issue by bhashemi** [chebfun/chebfun#1564]
One expects the function `sin(20+x+y)` to be rank 2 but here is what we see
`rank(chebfun2(@(x,y) sin(20+x+y)))`
`ans =
     4`

The tolerance that Chebfun2 uses here to chop a sequence of pivots is `tol = 2.2845e-15` while we have
`pivotValue(2) =   0.9608` and `pivotValue(3) =   -3.2196e-15`.

![untitled9](https://cloud.githubusercontent.com/assets/9217439/8772445/2f8c66f4-2ec4-11e5-87f4-9cf69c006f82.jpg)

Since I am not sure that there exists a universally best formula for tolerance, my suggestion is to add the following post-processing step to the chebfun2 constructor. As I discussed with `@jaurentz`, we can call the recently introduced `standardChop.m` on the sequence of pivots. 

My experiments suggest that this works fine and resolves this issue. This is important for my 3D experiments where the number `20` in `sin(20+x+y)` actually came from the function `sin(x+y+20*z)`.

**Comment by ajt60gaibb** [comment]
I take the view that there are always examples like this -- whatever you do.  Note that Chebfun does not always get the degree of a polynomial correct.  Moreover, this situation is seen all the time with the `rank(A)` command in MATLAB. The solution is `rank(A, tol)`. 

There was briefly a post-processing step as you describe in Chebfun2 in 2013 (a long time ago), but I removed it almost as soon as I put it in.  The reason was that it seemed to sometimes lose a digit or so of accuracy. Now that @bhashemi has the put in a better derivative-based error tolerance, I expect the situation is much better. 

A small pivot in GE does not necessary mean that GE does not need it for accuracy. It sounds strange, but for less smooth functions those pivots values behave less like singular values.   Have you tried your suggestion on less smooth functions? If chopping away those small pivots still hurts Chebfun2 for nonsmooth functions,  then just call `rank(f, tol)` if you need the numerical rank.  

Personally, I am not convinced that this example means that the Chebfun2 constructor should be changed.

**Comment by ajt60gaibb** [comment]
Should this be closed?

**Comment by bhashemi** [comment]
Thanks @ajt60gaibb . I think there are two different situations here. 
1) The `pivotValues` decay slowly in which case, as you said, we might lose some digits of accuracy if we do what I suggested. 
2) The `pivotValues` decay fast e.g., there is a gap between the last pivots (like in the above plot) in which case, I guess, not only we don't lose some digits of accuracy but also we construct cleaner chebfun2 objects.

However, I'm not sure how we can distinguish between these two cases. So, I think we can close this issue.

**Comment by ajt60gaibb** [comment]
This is a good point, but we are not sure how to improve the code. Close this for now.
