### ISSUE TITLE
Chebfun-related project: Chebfun in .NET

### ISSUE THREAD

**Issue by davidagross** [chebfun/chebfun#1571]
All, I'm writing because I am interested in, for various personal and professional reasons, porting / developing some Chebfun technology in .NET, specifically F#.

I'm hoping that it will simply be a public GitHub project under my account, and that someday it may even make it on the official [Chebfun-related projects](http://www.chebfun.org/about/projects.html) list.

As a curiosity, does anyone have any insight, suggestions, or preference as to what this should be called--for clarity, utility, and memorability--should public development on it get any traction?

- chebfun.NET
- chebfun.fs
- chebf#
- cheb#
- chebsharp
- ...

**Comment by trefethen** [comment]
David, that sounds very interesting.  Good luck and by all means let us know when things are developed enough to be pointed to.

Though legally I don't know if we own the name "Chebfun", it would be a bit odd for you to use a name beginning with "chebfun" since that might give the impression of being part of the same enterprise.  At our list of related projects I notice the appearance of pychebfun and libchebfun, but nothing so close as, say, chebfun.net.  So that's my preference: if your name contains the string "chebfun", I'd prefer that it not start with that string.

Best wishes for this.

**Comment by davidagross** [comment]
Thanks @trefethen and I'll definitely let you know when (if) things get there :smile: 

Yours is a poignant observation I didn't make. Taking a closer look at other projects it appears a common pattern would yield FsChebfun, so I'll throw that out as new straw name in the case anyone shows great preference or displeasure.

**Comment by davidagross** [comment]
A first pass that just gets `test_constructor_basic` running (on single domains) is now up at [FsChebfun](https://github.com/davidagross/FsChebfun) and I have the long term goal set of creating a PDF from values on equispaced points and inverting their CDF to draw samples from the provided distribution.  I'll be stitching together the behind-the-scenes to make this happen from what's available in Chebfun, but if anyone has any tips or would just like to contribute, please do!
