### ISSUE TITLE
Remove template 'headers' from CLASSDEF files. 

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1601]
When @aaustin141 and I were removing epslevels, a major source of frustration was the templating in the CLASSDEF files for each of the classes.

Since it's not clear that we gain anything from having these here (the descriptions you see in `>> doc chebfun` appear to be sourced from the m-files themselves, rather than the descriptions in the CLASSDEF), I propose they be removed.

**Comment by asgeirbirkis** [comment]
Is it possible to impose properties such as `hidden` and `private` outside the classdef files, or would you still include them in the classdef files?

I hadn't realised that `doc` actually grabs info from the m-files themselves, makes listing the standard public, non-hidden methods in the classdef files a bit less useful.

**Comment by aaustin141** [comment]
I think you're right that we can't impose method attributes outside of the classdef files.  Nevertheless, I still think it would be a good idea to get rid of all the declarations of the plain public methods with no special attributes.  The confusion that results when the classdef-declared prototype and the M-file declared prototype are out-of-sync is annoying, since the error messages you get when this happens don't do a good job of telling you what has occurred.

For instance, if the M-file prototype has 3 arguments and the classdef one has 2, MATLAB will silently take the classdef-declared prototype as the "right" one and give you a "too many arguments" error when you call the function with 3 arguments.  This looks _really_ mysterious if you've forgotten that the classdef declaration exists.  It's easy to waste 5-10 minutes wondering what on earth is happening if you haven't hit this before (or if you have but have forgotten, as has been the case with me).  Searching the Internet isn't very useful, since the error message is so common and usually applies to another problem.

Getting rid of the useless declarations has the additional bonus that the special status of methods with attributes will be highlighted instead of buried in a mound of noise.

**Comment by nickhale** [comment]
I think you still need to declare such properties inside the CLASSDEF file. However, it should suffice to declare the template as
```
methods ( Static = true )
    varargout = method_name(varargin);
end
```
in the CLASSDEF.

**Comment by asgeirbirkis** [comment]
Yes, I myself have run into the issue @aaustin141 describes, so I support this proposal; if I want to look at methods for a class, I usually go `>> methods chebfun` rather than looking into the classdef file.

**Comment by davidagross** [comment]
I second @nickhale here, that you do still need them in the CLASSDEF.  However, I believe that if you use `varargin` and `varargout` to obfuscate from MATLAB `nargin` and `nargout` (so that it's never out of sync with the signature in the M-file) then tab-completion at the MATLAB command line and in the editor "is broken" in that it will just show `functionName(...)` instead of the named function arguments that might be more helpful.

However, I believe this was a problem in 2012b and maybe now it's better, and it was also still a problem with non-static methods that took in `this` as it's first argument.  But it's something to check / think about while testing this out and hitting `clear classes` pretty hard.

**Comment by nickhale** [comment]
*bump*

**Comment by aaustin141** [comment]
Cross-ref. #888.
