### ISSUE TITLE
Computing PDE solns without caring how big TMAX is

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1648]
An matter has arisen in `pde15s/chebgui` calculations that I believe is important to making Chebfun exciting and impressive for users.  (The same matter arises in @Hadrien-Montanelli's stiff PDE solvers, though this issue is officially tied to `pde15s/chebgui`.)  Users love to be able to start a signal running and watch it go for a long time -- effectively forever.  For example, it should be possible to solve the Kuramoto-Sivashinsky equation on a time interval of thousands, and just happily watch the chaotic solution evolve as you talk to your friends about the weather or the latest James Bond movie.

Currently in the default `pde15s/chebgui` modes, however, this is not possible, because solutions are stored all along.  Moroever even if you solve on a modest-length integral, at the end you have to wait often a long time for a surface plot to appear.

I hope @asgeirbirkis can rejig things so that by default at least, we don't save solutions along the way and we don't attempt a waterfall plot at the end.  

This issue is important for the V5.3 release, since one thing we'd like to publicize with the release is that our PDE solutions have speeded up.

**Comment by nickhale** [comment]
I think the only way to do this is by adding an option to `pdeSet()`. If we did this, I'd be against it being the default mode, as that would be inconsistent with MATLAB's ODE solvers. Perhaps it would be OK if only `[t_init, t_final]` are passed as the time interval, but in that case we default to only 51 time steps anyway.

**Comment by trefethen** [comment]
Let me counterargue!  Throughout scientific computing, it is standard to store the time-histories of ODE solutions and quite exceptional to store the time-histories of PDE solutions, because they're just too darned big.  Sure enough, storing big time-histories in Chebfun is messing up our demos consistently, taking away much of the fun of solving PDEs.  Half the PDE demos in CHEBGUI lead to an embarrassing wait for the waterfall plot at the end, and most of the time the viewer is probably doing it for the movie, not the waterfall plot anyway.  I am eager to publicize fast PDE solving with V5.3, but I won't feel comfortable publicizing this so long as this problem persists.

**Comment by jrus** [comment]
If the solution evolves over time in a continuous way, wouldn’t it be possible in theory to store the time-history as a chebfun of one dimension higher? [This might take some trickery given uniformly spaced time steps, of course.]

**Comment by asgeirbirkis** [comment]
OK, I've done some experiments, and here are my observations. It'd be good to reach a consensus about our plan of attack before implementing anything:

1. If I replace the call to `chebfun/waterfall` at the end of the PDE solving process with simply evaluating the results on a 400 point Chebyshev grid, and call the built-in waterfall on the results, things are much faster.

2. The process though of going through the layers and getting the plotdata is actually fairly quick, so that was not the issue.

3. It was line 131 of `chebfun/waterfall` that was actually causing a lag,` % Plot the edges:
h2 = mesh(xx.', tt.', uu.', varargin{:});`. Everything above it in the code seemed to move quickly.

4. Thanks to some hunch, I tried removing the last argument to the call to mesh, and lo and behold, `h2 = mesh(xx.', tt.', uu.');` makes everything run faster. The `varargin` we were passing was the linewidth, so if I remove that from the call from the GUI code, everything gets so much faster in the GUI as wel!

5. Solving the Allen-Cahn PDE demo, storing the function at 51 intermediate timesteps, results in a `chebfun` of size approximately 275 kb, which on a modern computer is trivial. As @nickhale points out, storing 51 steps is the default behaviour when only the initial and final times are specified.

6. If we were to remove the waterfall plot from the GUI, there would be a decent amount of unused space  at the bottom of the movie figure. Not sure what we could use that space for instead (one idea might be a coefficient plot of the final solution, however, that doesn't look interesting for problem such as Allen-Cahn where the solution has decayed to zero).

7. During the PDE solve, most time is actually spent on plotting at each intermediate timestep (i.e. calling `drawnow`), the cost of doing the actual storage of intermediate solutions seems to be negligible.

So my proposal is:

1. Keep the waterfall plot in the GUI but without the thicker lines. I can show how much quicker it is at the next meeting.

2. Introduce an option about whether the history should be stored or not. What the default option should be, I'm not sure. Maybe instead of a Boolean, it could be a number, specifying how many intermediate timesteps should be stored (i.e. so that if it's 10, and we specify a vector with 100 elements as the time vector, only every tenth solution would be stored).

**Comment by trefethen** [comment]
@asgeirbirkis, thanks very much for investigating this.  I trust you will demonstrate things at our team meeting tomorrow.

The crucial things for me are that (a) a user doesn't waste a lot of time waiting for a plot they don't much care about and (b) a user running, say, the Kuramoto-Sivashinsky demo, should be able to increase the upper time limit to some huge number without running into trouble.

**Comment by asgeirbirkis** [comment]
Once #1660 gets merged, we'll have gotten rid of the delay after solving problems in the GUI while waiting for waterfall. The pdeSet option for determining how many steps should be stored requires some slightly more careful thinking and design, for example:

* Whether it should just be a Boolean or not
* What to do when the `tspan` vector has just two entries
* What we should do when a user passes a `tspan` vector with more than two entries (should we overwrite the number of timesteps with the number of timesteps returned?)
* How the `pdeSolve` codes (`pde15s` and `pde23t`) interacts with the new PDE functionality @Hadrien-Montanelli has been working on -- I'm expecting nothing will be stored there, so it'll be weird if `pde15s` does store solutions by default. I wouldn't be a fan of introducing some default behaviour now that could potentially change in next release. 

So I suggest we move this issue to the v5.4 milestone (I'm assuming `spin` will be part of 5.4, which means PDEs will without a doubt be a focus point for that release), and focus on getting #1660 merged (which is already included in the v5.3 milestone).
