### ISSUE TITLE
nonlinear ODE BVPs: discretize-then-solve?

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1693]
I would like to raise a fundamental issue for discussion (two specific questions appear at the end).  I am eager for comments from @asgeirbirkis, @tobydriscoll, @nickhale, and all others who may have views.  I would be glad to see comments too from @mike-giles, patrick.farrell@maths.ox.ac.uk, and @rjleveque.

As we all know, Chebfun solves linear ODEs by discretize-then-solve.  By this I mean that a standard spectral collocation method is carried out.  The only thing "Chebfun" about the process is that we automatically refine the grids until the constructor is "happy" with the solution obtained, so that at the end the solution is a chebfun, not just a discrete vector.  

Amazingly, Chebfun does its Newton iterations for nonlinear ODEs in the more challenging mode of solve-then-discretize.  By this I mean that Fréchet derivative operators are constructed in a more or less continuous manner.  Thus each Newton step might involve a different grid.  Now why do we do this?  Historically, the answer goes back six years or so.  We thought it would be fascinating to try solve-then-discretize, since it is so much in the Chebfun spirit of working with continuous analogues of familiar discrete algorithms.  Then @tobydriscoll and @asgeirbirkis  dazzled us all with how with the success of their implementation based on a continuous variant of Automatic Differentiation.  To everyone's surprise, we found that this way of solving ODE BVPs wasn't so inefficient.  I never claimed that this approach to nonlinear ODEs would beat standard methods in efficiency; I merely thought it would be _neat_.  (Also I thought it would be educationally interesting, since it enables people to see a Newton iteration in its pure, continuous form.  Alas, I am not aware that anybody has ever been taken with this capability.)

In all these years, I don't remember anybody ever asking us what price, if any, we pay for using solve-then-discretize.  But that's no reason why we ourselves shouldn't ask the question.  What was done for reasons of neatness six years ago probably could use a bit more justification in an era where with each passing year, our feeling grows that Chebfun represents the world's best general-purpose ODE solver (as measured by some blend of convenience, capability, and speed).  And the Chebfun team knows well that in a few crucial parts of the software, we already switch to discrete methods for speed.  The latest big one is ODE IVPs, which are solved by a standard marching method (by default ODE113) and only at the end converted back to chebfuns.

So here is my pair of questions for discussion:

(1) Do we pay a price in efficiency for using solve-then-discretize?  How great?

(2) Apart from neatness and education, does it bring us any benefits?  E.G., greater reliability?

**Comment by mike-giles** [comment]
Hi Nick,

In the adjoint community we face the question of adjoint-then-discretise or discretise-then-adjoint.

There I would say that the pros and cons are:

1) formulation and solver

discretise-then-adjoint is very "mechanical" in its application -- it dictates what the discrete adjoint equations are, and in most cases it guarantees you that the iterative process will be stable because the primal iterative process is stable.

On the other hand, with adjoint-then-discretise you have to construct the adjoint (in particular, formulating the b.c.'s for the adjoint can be non-trivial if you're starting from the strong not weak form) and then think about how to discretise it (potentially using a completely different method to the primal problem).

2) accuracy

With discretise-then-adjoint there can be issues with the adjoint solution near the boundaries, so that you may not get convergence in L_infty, but only in L_2, or even in H^{-1}.

With adjoint-then-discretise you will get the accuracy that comes from the new discretisation selected for the adjoint.


I don't know whether any of these comments are helpful in your context.

Cheers,

Mike




________________________________
