### ISSUE TITLE
SIMPLIFY for CHEBFUN2 (and CHEBFUN3)

### ISSUE THREAD

**Issue by Hadrien-Montanelli** [chebfun/chebfun#1709]
It's possible to simplify a `chebfun` f to a given accuracy with the `chebfun/simplify` command, e.g.: 
```
>> f = chebfun(@(x) cos(100*x))

f =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]      149      0.86     0.86 
vertical scale =   1 

>> g = simplify(f, 1e-6)

g =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]      129      0.86     0.86 
vertical scale =   1 
```

The `chebfun2/simplify` doesn't allow one to pass a tolerance:
```
>> f = chebfun2(@(x,y) cos(100*x) + y)
 
f =
 
   chebfun2 object (1 smooth surface)
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        2     [-0.14 -0.14  1.9  1.9]
vertical scale =   2 

>> g = simplify(f, 1e-6)
Error using separableApprox/simplify
Too many input arguments.

Error in chebfun2/simplify (line 11)
[varargout{1:nargout}] = simplify@separableApprox(varargin{:});
```

I'd expect this to work for `chebfun2` objects as well as `chebfun3` objects. (I don't mean a reduction of the rank, I mean lower degrees for the underlying 1D chebfun's.)

**Comment by ajt60gaibb** [comment]
OK. Fine by me.

**Comment by Hadrien-Montanelli** [comment]
Great!

**Comment by jrus** [comment]
Would also be great to see rank reduction for rows/columns with coefficients falling entirely below the tolerance. Right now I sometimes get twice as high a rank as my data supports, with half the rows/columns just being noise. It’s easy to manually strip these out, but having it be a part of `simplify` seems logical.

**Comment by ajt60gaibb** [comment]
Do you have an example @jrus?   Can you add an issue (if you have not already)?  There may be a few simplifies missing in some of the `chebfun2` commands.

**Comment by jrus** [comment]
Github doesn’t want me to attach a matlab `.mat` file here. :/

Anyway, as an example just take the values of any arbitrary smoothish function on a grid of tensor product Chebyshev points, e.g. 257 by 257 points, add a bunch of random noise at the scale of, say, `1e-8`, and then pass the grid of data into the `chebfun2` constructor. It will happily keep adding rows/columns until it hits 14 digits of precision, and keep the length of each row/column the full original length, even though most of the result is pure noise. `simplify` then doesn’t do anything.

Here’s a `plotcoeffs` picture:
<img width="1165" alt="screen shot 2016-01-15 at 4 56 53 am" src="https://cloud.githubusercontent.com/assets/83411/12353535/c617ecc6-bb44-11e5-968c-380f30cba219.png">

**Comment by jrus** [comment]
I don’t actually have the best sense of what the right behavior is for "chopping" the rows and columns of a chebfun2. It’s not clear at exactly what point the rank should be cut off for a particular desired tolerance, or whether all of the columns should be chopped at the same number of coefficients.

For example, in the coefficient plot below (not the same example as the previous comment), I’ve highlighted one column’s coefficient magnitudes in yellow. There seems to be some structure up through about degree 190, and then after that it seems like mostly noise (of larger magnitude than the earlier structure). But for earlier columns, there seems to be useful structure all the way out to about 250 coefficients. I’m not sure if the usual heuristics in `standardchop` are going to handle this case. [Or maybe the column I’ve highlighted should just be dropped altogether...]
<img width="655" alt="screen shot 2016-01-17 at 4 18 20 pm" src="https://cloud.githubusercontent.com/assets/83411/12381010/f6f3c304-bd35-11e5-9d69-11715768d8cd.png">

**Comment by ajt60gaibb** [comment]
Your examples are actually related to making `chebfun2` objects from discrete data and what you are seeing is desired behavior. An analogous behavior occurs in Chebfun. I guess the user is expected to `simplify` after-the-fact if desired. In Chebfun2 this will be done with `simplify(f, tol)`, once the issue here is resolved.   

Thanks for bringing this up.  It is a good point.   We definitely do need a `simplify(f, tol)` option. 

I think `standardchop' applied to an arbitrary linear combination of the columns (rows) should do the trick. 

For the `simplify` command on the column (rows), we require the length of the columns (rows) to all be the same for vectorization in subsequent operations. It is often much faster this way in MATLAB.

**Comment by jrus** [comment]
>  I guess the user is expected to simplify after-the-fact if desired.

That seems entirely reasonable. That’s why I chimed in with “Would also be great to see [`simplify` also apply a] rank reduction for rows/columns with coefficients falling entirely below the tolerance.”

>  we require the length of the columns (rows) to all be the same for vectorization in subsequent operations

Sure. But in principle some columns could be chopped shorter and then padded out with zeros.

As I said, I don’t have a good sense of what the right (simplest, most accurate, most robust, ...) behavior is for deciding the proper rank and chop point for each column when simplifying a chebfun2. Due to the nature of later chebfun2 columns as residuals after lower-rank approximations have been subtracted off, I suspect the type of structure seen in the coefficient magnitudes will often be somewhat different from that seen in typical one-dimensional chebfun approximations.

**Comment by ajt60gaibb** [comment]
Ah, I missed your rank comment. I see. 

One thing to keep in mind:  It is computationally expensive to simplify the rank of a `chebfun2` because the SVD has to be computed. Usually we just have the Gaussian elimination pivots, which do not tell us much.  I wonder how to give the user this option because I think `simplify(f,tol)` should just do the columns and rows to keep it fast.

**Comment by jrus** [comment]
You don’t think it’s sufficient to just use the gaussian elimination pivots and chop off any rows/columns for which the max value falls below the tolerance?

**Comment by ajt60gaibb** [comment]
I do not think that pivots are enough, especially when the function is not smooth. It would work 90% of the time. 

The command `[U,S,V] = svd(f)` calculates the SVD of the chebfun2 `f`. If `k=10`, then `fk = U(:,1:k)*S(1:k,1:k)*V(:,1:k)'`constructs the best rank 10 approximation to `f`.

**Comment by jrus** [comment]
Aha, thanks.

Do you have any advice about interpreting the coefficient magnitudes for an SVD-generated low-rank approximation? I have a reasonable enough understanding of what the coefficients mean when they’re coming from GE pivots, and in principle I understand the steps to make the SVD, but the coefficient plot looks quite different than the GE version.

For instance, to go back to the example above:
```matlab
f = @(x, y) 1 ./ (25*x.^2 + 25*y.^2 + 1);
[x, y] = meshgrid(chebpts(257), chebpts(257));
fxy = f(x, y) + rand(257) * 1e-8;
cheb = chebfun2(fxy);
k = 20;
[U,S,V] = svd(cheb);
cheb20 = U(:,1:k)*S(1:k,1:k)*V(:,1:k)';
plotcoeffs(cheb20)```

results in the following:
<img width="1031" alt="screen shot 2016-01-18 at 4 46 11 pm" src="https://cloud.githubusercontent.com/assets/83411/12406565/024881fe-be03-11e5-881f-bb28037cef17.png">

Where the first few rows coefficient magnitudes drop fastest, and later rows have coefficient magnitudes near 1e-1.

**Comment by jrus** [comment]
Is there a computationally reasonable way to compute some kind of norm for residuals beyond a particular rank, so I can judge where to chop the SVD without losing useful information?

I was trying to use:
```matlab
abs(max2(U(:,k:end)*S(k:end,k:end)*V(:,k:end)'))
```
but while that seems to take only a second for values of k near the end, at some point it transitions to basically stalling indefinitely. Is there some limit to the rank of a chebfun2 where max2 is fast? Or is it just that the residuals get too wiggly and so there are too many local extrema to examine in a reasonable amount of time, or...?
