### ISSUE TITLE
MESHGRID vs NDGRID for CHEBFUN2 and CHEBFUN3

### ISSUE THREAD

**Issue by Hadrien-Montanelli** [chebfun/chebfun#1710]
Two- and three-dimensional grids can be generated by the `meshgrid` and `ndgrid` commands. For example:

```
>> tt = chebpts(3);
>> [xx, yy] = meshgrid(tt)

xx =
    -1     0     1
    -1     0     1
    -1     0     1


yy =
    -1    -1    -1
     0     0     0
     1     1     1

>> [xx1, yy1] = ndgrid(tt)

xx1 =
    -1    -1    -1
     0     0     0
     1     1     1


yy1 =
    -1     0     1
    -1     0     1
    -1     0     1
```

Note that `xx1 = yy = permute(xx, [2 1])` and `yy1 = xx = permute(yy, [2 1])`. Similarly in 3D,

```
>> [xx, yy, zz] = meshgrid(tt);
>> [xx1, yy1, zz1] = ndgrid(tt);
```

generate grids such that `xx1 = yy = permute(xx, [2 1 3])`, `yy1 = xx = permute(yy, [2 1 3])` and `zz1 = zz`. 

In 2D, one can evaluate a `chebfun2` at a grid generated by either `meshgrid` or `ndgrid`. However, to construct a `chebfun2` from discrete data, these data have to come from a grid generated by `meshgrid`.
In 3D, the current behaviour is that one can also evaluate a `chebfun3` at a grid generated by either `meshgrid` or `ndgrid`, but the construction process from discrete data assumes that the grid was generated by `ndgrid`. I don't like this inconstancy. 

Because we're using `meshgrid` for `chebfun2` objects, when`f` is a `chebfun2` then `diff(f,1,1)` is (the partial derivative) df/dy, while `diff(f,1,2)` corresponds to df/dx. This seems unnatural to me but I can live with it.

Behnam chose `ndgrid` for two reasons: A, if we were using `meshgrid` for `chebfun3`, then, for example, `diff(f,1,1)` would be df/dy, `diff(f,1,2)` would be df/dx and `diff(f,1,3)` would be df/dz, and B, `meshgrid` doesn't generalise to dimensions > 3 while `ndgrid` does.

It's clear that changing the behaviour of Chebfun2 is a lot of work and we probably don't want to do that (the papers/guide assume this behaviour), but I still wanted to raise this issue.

**Comment by ajt60gaibb** [comment]
This was brought up by me and Benham in the Chebfun meeting in June 2015 when I was in Oxford. @bhashemi knows the full story.  I cannot remember what we decided to change. 

All I know is that I am not volunteering to implement the change. :+1:

**Comment by Hadrien-Montanelli** [comment]
Fair enough @ajt60gaibb. Are you happy if we do the change?

**Comment by ajt60gaibb** [comment]
I cannot remember what we decided to change. I am happy with whatever we decided back in June, but I do not think it was to swap the roles of `x` and `y` throughout `chebfun2`, `chebfun2v`, and `chebop2`.  That would take several weeks to implement and test (I suspect). 

Mathematically, both ways are equally valid. So as a mathematician, I do not mind what happens.   

There are several papers that this (mathematically trivial) change makes obsolete: 

1. The Chebfun2 paper, 
2. The continuous analogue of matrix factorizations, 
3. The chebop2 (rectpde) paper, 
4. The spherefun paper, and
5. The diskfun paper (in preparation).

So, maybe we should wait for opinions from @trefethen, @gradywright, @heatherw3521, and @dlfivefifty first.

**Comment by dlfivefifty** [comment]
I’m in favour of swapping, it feels more natural to me for the columns to be coefficients in x, for some reason.  This is also compatible with our "A practical framework for infinite-dimensional linear algebra”  paper.

**Comment by ajt60gaibb** [comment]
Looks like I am on my own.

**Comment by bhashemi** [comment]
@ajt60gaibb , beyond raising the issue and having a discussion in the meeting of June 2015 about this, I am not sure we made an explicit decision at that time. All I remember is that nobody was ready to suggest that ``chebfun3`` should replace using ``ndgrid`` by ``meshgrid``. But similar to @Hadrien-Montanelli , I also feel that we should finally make a decision and choose one. My preference is not changed and is still the same as what mentioned above by @Hadrien-Montanelli .

**Comment by jrus** [comment]
W/r/t breaking changes compared to papers, can the online pdf versions at least be amended?

**Comment by bhashemi** [comment]
In case we decided to change the codes in ``chebfun2``, I can do the required changes, though I am not sure how quick it would be.

**Comment by dlfivefifty** [comment]
I think expecting papers to be “forward compatible” would be burdensome, as it makes the time cost of breaking changes in Chebfun very high.

**Comment by jrus** [comment]
To clarify: I’m not commenting on whether or not you should avoid breaking changes in the code. Assume for the sake of argument that you’ve decided to make this change. What I wonder is whether the online pdf versions of previously published papers (hosted at chebfun.org or arxiv or wherever) can be amended to match the new API. In this the changes should be minor, e.g. swapping `[a b] = meshgrid(x, y)` → `[b a] = ndgrid(y, x)`.

**Comment by gradywright** [comment]
You are not alone @ajt60gaibb.   I am also not in favor of making the change.  I think most users of matlab are familiar with the `meshgrid' format for the grid of values when dealing with 2D functions.

**Comment by heatherw3521** [comment]
Overall from the perspective of someone really new to numerical computing (but obviously very influenced by Grady), I definitely think meshgrid is the more intuitive one and matches up with how I think about discretizations. I assume other student users would have a similar intuition. For people still learning, this is important because they don't have the experience to always recognize quickly that something is amok in the results, or figure out exactly what that something could be.

**Comment by jrus** [comment]
This is likely obvious to everyone here, but the full context here is:

* One mathematical convention dictates that when making two-dimensional plots, the first axis is horizontal and the second axis is vertical. This also follows European writing systems which read left-to-write and then top-to-bottom.

* A different mathematical convention dictates that when dealing with two-dimensional matrices, the first index should represent the columns and the second index should represent the rows. Matlab, after Fortran, follows this convention; C and various other programming languages follow the opposite convention, where the first index tracks row position.

* When using the entries in a matrix to represent a grid of function values over a two dimensional space, these two conventions can come into conflict. The more consistent/generalizable thing to do in a computing context is to have the order of indices for grid construction follow the order of indices of the data structure, instead of arbitrarily reversing the first two indices to match the plotting convention. Unfortunately, because Matlab’s `meshgrid` uses the row-major convention while its matrices generally are column-major, `meshgrid`’s usefulness is limited to two dimensions, and for higher-dimensional grids it was necessary for Mathworks to add an `ndgrid` function whose indices match the data structure order.

**Comment by ajt60gaibb** [comment]
It looks like Chebfun2 and the `separableApprox` class are staying with `meshgrid` because I am not willing to implement `ndgrid`, and no-one else is stepping forward. This is the more natural convection anyway from my point-of-view.
