### ISSUE TITLE
Dimension of .FUNS in CHEBFUN objects?

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1752]
The dimension of the `.funs` is inconsistent. Sometimes it is an `nFuns x 1` array, sometimes it is `1 x nFuns`. I think the latter is incorrect, since we typically think of vertical as being the continuous dimension.

Usually this isn't a problem, since we run through the `.funs` field in `for` loop using a single index (and MATLAB is agnostic to dimensions in this usage). However, if we want to use `cellfun()` for efficiency/clarity, this can cause problems. (See for example the discussion in #1751.)

**Comment by jrus** [comment]
I think this is because the API design for transposed array-valued chebfuns was done in a somewhat ad-hoc way. It will take a considerable amount of work to figure out what layers of the stack actually need to know about transposes and then clean up all the related code. Probably at least a few days of full time effort.

**Comment by nickhale** [comment]
The transpose state doesn't affect the orientation of the `.funs` array. It's just a flag.

**Comment by jrus** [comment]
Isn’t it related though? What other reason would funs be oriented the other way?

I agree with you that from what I understand about chebfun internals, the funs cell should always be a column-vector shape.
