### ISSUE TITLE
scaling pivot values vs scaling basis vectors in Chebfun2/3

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1753]
@ajt60gaibb, we would be glad for you to comment on this.  Of course others may have views too.

Normally in mathematics when we have an expansion of a function into SUM_k  a_k v_k where a_k is a coefficient and v_k is a vector, we expect the vectors to be of size O(1) and the coefficients to decrease to 0 -- or on a computer, to 1e-16.

Chebfun2 seems to have taken a different choice.  The expansion is SUM_k a_k r_k c_k where r stands for row and c stands for column.  Both the rows and the columns decrease in size to 1e-16, forcing a_k to increase to 1e+16.  This oddity is disguised by the fact that if you ask for the "pivot values", what you are given are the reciprocals 1/a_k.  (Example plot below.)

Chebfun3 currently follows Chebfun2, with the result that the oddity is now squared.  We have SUM_k a_k r_k c_k t_k , where t stands for "tubes".  Now the columns, rows, and tubs all decrease to 1e-16, so a_k has to increase to 1e32.  

@ajt60gaibb, is there some good reason why we ought to write things this way, or should Chebfun3 break with the style of Chebfun2?  (Whether Chebfun2 also gets reformulated is a question for another day.)  Let me emphasize that I'm not referring to any aspect of the algorithm itself, merely to how we scale the outputs from that algorithm.

Here's an example illustrating the current scaling in Chebfun2.  We take a 2D Runge function and execute plotcoeffs.  This reveals that the successive functions defining the x and y dependences are scaled so as to decrease toward 1e-16.  Thus the final row*column product in the sum is down at the level of 1e-32, requiring a pivot of size 1e16 to bring it back up to the level of machine precision.

This message written in collaboration with @bhashemi.

```
f = chebfun2(@(x,y) 1./(10+x.^2+y.^2),[-1 2 -1 2]); plotcoeffs(f)
```

![runge2d](https://cloud.githubusercontent.com/assets/3601488/12888620/f6844742-ce72-11e5-91bf-b76102a4eb4d.png)

**Comment by ajt60gaibb** [comment]
Mathematically, I agree, it does not matter.  Practically, we used to have to worry about `epslevels`. Is this still a valid concern?

Mathematically, I have no strong feelings.   The discrete analogue to this question is: Do you prefer  `A = LU` or `A = LDU` with various combinations of `L` and `U` being unit triangular? In some sense the choice is arbitrary and the scaling can be moved around. Chebfun2 has neither `L` nor `U` as unit triangular. Theoretically, since we only need SUM_k a_k r_k c_k to be accurate, I do not think it matters. 

However, it used to make a BIG difference in Chebfun due to `epslevels`.   The columns and rows of a chebfun2 object are stored as an array-valued chebtech object.  When `epslevels` were first around an array-valued chebtech had an `epslevel` that was a single number (later Nick Hale may have added a vector `epslevel` property).   The columns of a chebfun2 are usually accurate to 16 absolute digits, but the last column has essentially no relative accuracy. If one scaled the columns to have an absolute maximum of one, say, then the last column would need an `epslevel` of roughly `1e-1`, while the first column would need an `epslevel` of `eps`. 

Now that the `epslevel` property has been removed, I am not sure how much the scaling of the column, rows, or fibers makes a difference.

**Comment by ajt60gaibb** [comment]
Maybe @nickhale or @aaustin141 would like to comment too.

**Comment by nickhale** [comment]
There used to be some (read "a lot") witchcraft in `simplify()` for array-valued objects to ensure that we 'did the right thing'. In particular there was some relationship between the 'global' epslevels and vscales and the 'local' ones of each column. Unfortunately I no longer recall the details.

**Comment by jrus** [comment]
>  is there some good reason why we ought to write things this way,

Personally I find that this makes the coeff plots a lot easier to interpret, as it makes the column/row coefficient magnitudes stay at the same relative scale. Even if internally the coefficients are all scaled some other way, it might be nice if plotcoeffs could rescale them to the current style for plotting.

**Comment by jrus** [comment]
I’ve been thinking about this a bit more today.

Can I recommend storing the coefficients normalized by column, but then scaling them by the pivot values for display in `plotcoeffs`? (See the issue linked immediately above.)

I’d actually also recommend scaling by the norm of the pivot value array, so that the overall norm of all the coefficients in the plot is 1: this makes `plotcoeffs` show a consistent relative size regardless of the scale of the chebfun. Possibly even normalize the vector of pivots stored internally and include an extra "global pivot value" multiplier.

For simplification, the target tolerance for each column can be scaled by the pivot value and the norm of all pivots, so that the appropriate relative accuracy is .

This set of choices would make pivot values and coefficient values easy to reason about and easy to compare across chebfuns of different dimension.
