### ISSUE TITLE
Cummax is unsupported in Pre-R2014b MATLAB

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#1810]
According to http://uk.mathworks.com/help/matlab/ref/cummax.html, Matlab introduced the `cummax()` function in R2014b.

According to http://www.chebfun.org/download/, Chebfun supports R2009a or later.

Either we need to change the version we support (2014a isn't *that* old) or we need to remove `cummax()`. (Since #1794 offers only a small cosmetic improvement, my vote is for removing `cummax()`.)

Thanks to Anne Greenbaum for bringing this to my attention.

**Comment by trefethen** [comment]
Ah, I'm sorry.  This is my fault for suggesting the use of `cummax`.  It was Folkmar Bornemann who pointed out the possibility to me, and it never occurred to me that `cummax` might be a very recent feature.

With apologies to @jaurentz, to whom I have assigned this issue, may I request that you modify standardChop again so that it works the old way -- while leaving the cummax code there in the comments with an indication that this is "really" what's going and and we should switch to it after a few years?  Meanwhile in our paper for _TOMS_, which has been provisionally accepted subject to revision, I think we should publish the `cummax` version of the code, perhaps with a comment or footnote to explain.
