### ISSUE TITLE
No join method for chebfun2 objects 

### ISSUE THREAD

**Issue by ajt60gaibb** [chebfun/chebfun#1857]
```
u1 = chebfun2( rand(3), [-2 0 -1 1]  ); 
u2 = chebfun2( rand(3), [0 2 -1 1] ); 
u = join(u1, u2);
Undefined function 'join' for input arguments of
type 'chebfun2'.
```

**Comment by trefethen** [comment]
It seems to me that there shouldn't be a `join` method for Chebfun2.  In 1D Chebfun, any two chebfuns can be joined because we have piecewise representations.  In 2D, for fundamental reasons, we don't have piecewise representations, so usually a join wouldn't make sense.  (Apologies if I am missing something.)

**Comment by ajt60gaibb** [comment]
You are right in general. I was trying to stitch a smooth function back together and hoping for a command to do this in low rank form.
