### ISSUE TITLE
bail out of ODE IVP if solution grows too big

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1964]
In working on our new book _Exploring ODEs_, I've found that Chebfun does almost everything I want cleanly and easily.  The main exception on my mind now is the problem of solutions to ODE IVPs blowing up.  Many equations, like y' = y^2, have solutions that blow up to infinity.  Currently you have to set the time interval [0,T] diabolically to get what you want -- usually requiring a lot of ugly experimentation.  This gets seriously annoying when you want to plot multiple trajectories on a single phase plane! -- for each one needs a different T.  As a result, for the most part the phase plane plots in the book are disappointing.

I propose that we solve this problem by enabling users to set a cheboppref `maxnorm` whose effect would be that if the norm of an ODE IVP solution passes this prescribed number, the computation is stopped.  If this happens at time Tc < T, say, where you're computing on an interval [0,T], then Chebfun could return the solution as a chebfun defined on all of [0,T] but with value over [Tc,T] equal to NaN.

Presumably `maxnorm` will default to infinity, and I propose that it should be easily settable by the user following the `chebfuneps` pattern, e.g.
```
chebfuneps 1e-12
maxnorm 100
```
Here's an example.  I picked the coefficient 0.088 here carefully! -- if you change it to 0.09 you're sunk.
```
T = 30; N = chebop(0,T); t = chebfun('t',[0,T]);
N.op = @(t,y) diff(y,2)+y-.088*y^3; N.lbc = [-1; 0];
y = N\sin(0.05*t); plot(y,diff(y))
ylim([-1.5 3.8]), axis equal
xlabel('$y$'), ylabel('$y''$')
```
Here's the plot:

![duffing](https://cloud.githubusercontent.com/assets/3601488/17808129/24d61c94-6606-11e6-898c-99646b845092.png)

@asgeirbirkis, it would be wonderful if you have time to do this, but if not, would you at least be able to comment on how this proposal looks to you and what you think would be involved in implementing it?  Thanks.

**Comment by asgeirbirkis** [comment]
@trefethen In the case of coupled systems, should the setting for the ``maxnorm`` property you propose be a vector?

**Comment by trefethen** [comment]
Yes, that's what I had in mind.

**Comment by asgeirbirkis** [comment]
On `feature-cheboppref-maxnorm`, there is now a basic `maxnorm` functionality implemented. The case that's not dealt with is what happens when we have breakpoints already in the problem (e.g. from a constant that consists of multiple pieces), but that should be possible to implement as well.

Examples:

```
cheboppref.setDefaults('maxNorm',10)
T = 30 ; N = chebop(0,T); t = chebfun('t',[0,T]);
N.op = @(t,y) diff(y,2)+y-0.09*y^3; N.lbc = [-1; 0];
y = N\sin(0.05*t); plot(y,diff(y))
xlabel('$y$','interpreter','latex'), ylabel('$y''$','interpreter','latex')
```
produces

![maxnorm10](https://cloud.githubusercontent.com/assets/3543429/18029559/11286448-6c93-11e6-8b2c-566a6885eb72.png)


and
```
cheboppref.setDefaults('maxNorm',15)
T = 30 ; N = chebop(0,T); t = chebfun('t',[0,T]);
N.op = @(t,y) diff(y,2)+y-0.09*y^3; N.lbc = [-1; 0];
y = N\sin(0.05*t); plot(y,diff(y))
xlabel('$y$','interpreter','latex'), ylabel('$y''$','interpreter','latex')
```
produces

![maxnorm15](https://cloud.githubusercontent.com/assets/3543429/18029560/15afb7c8-6c93-11e6-83e8-60e06cd54032.png)


It also works for systems, here we break Lotka-Volterra if the `v` component exceeds 5:

```
N = chebop(@(t,u,v) [diff(u)-2.*u+u.*v; diff(v)+v-u.*v], [0 10]);
N.lbc = @(u, v) [u-3; v-1];
options = cheboppref();
options.maxNorm = [1 5];
[u, v] = solveivp(N, rhs, options);
plot([u, v], 'LineWidth', 2)
title('IVP solution'), xlabel('t'), legend('u','v')

```


![maxnormlv](https://cloud.githubusercontent.com/assets/3543429/18029561/1bb7c872-6c93-11e6-92e9-fe54fadbec0b.png)

At the moment, the option of easily changing the option from the command window hasn't been implemented (none of the `chebopprefs` can be set that way at the moment). It can either be set globally, e.g. `cheboppref.setDefaults('maxNorm,10)`, or by passing a `cheboppref` object to the solver. It's trivial to implement though if we decide that's what we want.

**Comment by trefethen** [comment]
I've just tried this and I *LOVE IT*!  This will change everything in writing _Exploring ODEs_.  Thank you so much @asgeirbirkis.

**Comment by nickhale** [comment]
I haven't looked at the code, but I guess you're achieving this via the `'Events'` option in `odeset`? Is there scope for allowing more general event detection in `chebop` solves as in `ode45`? 

Since we haven't thought of it until now, probably not, but what made me think of it is that next week in class my students will be solving a Lotka-Volterra system with `ode45` and they have to tell me when the number of predators equals the number of prey for the first time. 

Of course, because Chebfun is awesome, this is actually a simple roots calculation to do AFTER the solve, but other than this new max-norm functionality, `chebop` doesn't allow stop-on-event.

**Comment by trefethen** [comment]
Interesting idea @nickhale, though what I need urgently for _Exploring ODEs_ is just the `maxNorm` functionality.  Alas, my attempt to quietly set a default `maxNorm` of 10 breaks down in Chapter 2 of the book, where I solve an ODE with a nonsmooth term.

**Comment by asgeirbirkis** [comment]
@nickhale: Yes, this is achieved with the `events`  option in `odeset`.  I had actually started thinking about whether we could allow passing an anonymous function, and via the `treeVar` trickery, construct the corresponding stopping function for the ode solver. I'm actually pretty optimistic that might work, will give it a go coding it.

@trefethen: I should be able to get this working with breakpoints this week, just a matter of bookkeeping for all the different pieces of the solution and gluing them correctly together!

**Comment by asgeirbirkis** [comment]
I'm optimistic that it'll be possible to deal with more general events through the `treeVar` mechanism. However, for now, `maxNorm` was more straightforward to implement; I might try to generalise the functionality at a later date.

The PR #1975 now deals with this, note that differently from the discussion above, the functionality is achieved via the `chebop` object rather than `cheboppref`, so I opened a new branch with a different name to reflect the chance.
