### ISSUE TITLE
`eig` vs. `eigs`, `svd` vs `svds` for a chebfun2

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#1971]
When should we say `svd` and when should we say `svds`?  When should we say `eig` and when should we say `eigs`?  Here are some thoughts prompted by recent developments of @bhashemi and @nakatsukasayuji concerning eigenvalues and singular values of 2D structures.

For chebops, which typically represent differential operators, we have long required `eigs`, since there are infinitely many eigenvalues and we're only computing a finite number.  Indeed, `eig` yields an error message.  This seems absolutely right and I recommend no change.

But for a chebfun2, we have long had a command `svd`, not `svds`!  Is this inconsistent, since after all, a function f(x,y) will have infinitely many singular values?  My first thought was yes, it was inconsistent.  However, there is a difference between a chebop and a chebfun2 that perhaps provides consolation.  A chebop is a lazy object in that it does not come with an a priori fixed number of eigenvalues; in that sense it is truly infinite-dimensional.  A chebfun2, by contrast, is an object of fixed rank, even if it's an approximation to something of infinite rank.  So maybe `svd` isn't so crazy... and it's interesting that we don't even allow `svds`.

This comes up because @nakatsukasayuji and @bhashemi are likely to implement a new eigenvalue calculator for chebop2 objects.  Should they call it `eigs` (true to the Chebfun spirit) or `eig` (like the existing `svd` command), or both?

For further perspective I note that in Matlab, if A is a rectangular matrix, you have to type `svd(A,0)` or `svd(A,'econ')` to get the "skinny" svd, whereas for a decade we've allowed users to type `svd(A)` for the continuous analogue involving Chebfun quasimatrices.  We decided that forcing users to type `svd(A,0)` would be just too annoying.   Similarly with `qr`.

So my proposal is: `eig` is OK for a chebfun2; we don't need to insist on `eigs`.  But I'd be interested to hear views from @ajt60gaibb and others.

**Comment by ajt60gaibb** [comment]
I am little confused if we are talking about `eigs` in `chebfun2` or `eigs` in `chebop2`. I feel differently about them. 

Here are my thoughts: 

I like the idea of sticking with `eig` for `chebfun2` (in keeping with `chebfun2/svd`).  The integral operator with kernel `f(x,y)`, where `f` is a chebfun2 has finitely many nonzero eigenvalues, because `f` is of finite rank. The eigenvalue command is delivering all the possible nonzero eigenvalues it can: making it an `eig` (if the infinite number of zero eigenvalues are ignored) as opposed to an `eigs`.

For `chebop2`, I am supporting an `eigs` command.  Even after `chebop2` has truncated the splitting rank of a partial differential operator, the operator has (potentially) an infinite number of nonzero eigenvalues. An eigenvalue command in `chebop2` would have to deliver a subset of them, making the command an `eigs`. 

There is an anomaly here: The `svd` command in `chebop2`. But, I have been meaning to rename it for a while.  The `svd` command in `chebop2` is not really doing the operator analogue of a singular value decomposition.  Instead, it is doing a splitting rank decomposition of a tensor of variable coefficients for the partial differential operator derived from a tensor-train decomposition.
This is needed to automatically discretize partial differential operators, but the command should not be named `svd`.

**Comment by nakatsukasayuji** [comment]
We are a bit confused here. We agree that eig is appropriate for a chebfun2 object, and that's what we implemented in feature-chebfun2-eig today. 

For chebop2, however, we haven't done anything (and not even thought about it), and there doesn't seem to be a code chebop2/eigs (or eig). We agree that if there is a code, then it should be eigs. 

Behnam and Yuji

**Comment by ajt60gaibb** [comment]
Great!  I will take a look at the branch.  

I guess the title of this issue should be " `eig` vs. `eigs`, `svd` vs `svds` for a chebfun2`".  

I suspect an `eigs` command for a `chebop2` is going to be very involved.  More so than `chebop/eigs`.

**Comment by trefethen** [comment]
My apologies @ajt60gaibb and others -- it was a mistake on my part to put `chebop2` in the title of this issue.  I meant `chebfun2`, and I've now made the correction.
