### ISSUE TITLE
Spherefun: plot equator and Greenwich meridian by default

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2007]
John Boyd (jpboyd@umich.edu) has been visiting Oxford and has made a suggestion about Spherefun based on decades of experience with computing on the sphere.  Many people active in this area have the habit of including a circle for the equator and another circle for the Greenwich meridian in every plot.  He suggests, and I agree with him, that Spherefun should do the same.  Of course this could be a feature on by default but turn-offable.  What do you think, @gradywright and @heatherw3521 and @ajt60gaibb?

**Comment by gradywright** [comment]
I like the idea, but I'm not sure I want it to be the default setting.  I could be convinced (especially since John Boyd suggests it), but there needs to be a _very simple_ way of turning it off.  

Right now there is the `spherefun.plotEarth` method for including a plot of the coast lines, which I find more useful than the equator and prime meridian when dealing with geo-related data.  

Some additional questions:
1.  Should this also be the default for `contour`.
2.  Same question for `quiver`.
3.  What should the default color be?

I'm happy to hear the thoughts of others, especially @ajt60gaibb and @heatherw3521.

**Comment by ajt60gaibb** [comment]
Sounds good. I think the default should stay the same, though, but with a simple way to draw the two circles.    In this scenario, we could have the same option for most of the spherefun plotting commands.

**Comment by heatherw3521** [comment]
I googled some things related to functions on spheres and it does seem as if  a lot of the pictures include something like a lat-long grid, a plot of the coastlines, literal north/south poles, or the meridian/equator circles. So I agree. I have no preference about default/not default, except that perhaps we should allow someone to change the default to what they like,  instead of always having to type in a command whenever they plot. 

1. and 2. I think we should be consistent across visualization commands. 
3. i think black is the best color because it is rarely used to denote values in colormaps.
