### ISSUE TITLE
arbitrary rotations for `spherefun` and `spinsphere`

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2047]
In spherefun, it's all too easy to generate functions that have a special relationship to the axes -- e.g. with `spherefun.sphharm`.  Computations based on such functions will typically retain those symmetries.  I worry that we don't check enough that the same functions would be correctly represented if they weren't aligned with the axes.

Therefore I urge that a few tests be put in, initially in Spherefun and then in spinsphere, to make sure that when a function (resp. initial condition) is rotated in an arbitrary way on the sphere, the solution rotates the same way.  We should achieve this at least to many digits if not necessarily to 16 digits!

@Hadrien-Montanelli has agreed to let me assign this to him.

But this gets me thinking.  What's the mathematics of rotating a function on the sphere?  Obviously it's elementary in principle, but maybe a bit tricky in practice... so should we have a spherefun code to do this easily?  (One of my old index card notes is called "How far is Perth from Boston?".  I found it embarrassingly tricky to figure out the answer.  Of course any 19th century mathematician could have done this easily.)

**Comment by gradywright** [comment]
I put a `rotate` function in Spherefun, but it's horribly slow when the rank/lengths of the `spherefun` are high.  The issue is that my (potentially naive) implementation does not allow the operation to be vectorized nicely.  I would be very pleased if someone could come up with a fast method.   

Euler angles and quaternions are the key to rotation on the sphere.

**Comment by trefethen** [comment]
Thanks @gradywright.  I see there's no test function for `spherefun/rotate` -- perhaps @Hadrien-Montanelli (or you) will write one?  In my opinion, as expressed above, `spherefun/rotate` should then be called frequently in tests of other things in spherefun and spinsphere.  Let's face it, idiosyncrasies associated with grids and poles are *the* problem in this business; we need to be monitoring all the time whether we are successfully avoiding them.

**Comment by jrus** [comment]
You almost surely want to use a quaternion representation internally, possibly with other representations available as optional front-end APIs (e.g. you can take in direction vector + angle, Euler angles, 3x3 matrices, or whatever).

Quaternions are easy to work with and efficient to compose with each-other without introducing numerical artifacts.

Once you have a quaternion which you want to apply to a list of cartesian (*x*, *y*, *z*) coordinates, you can easily turn it into a 3x3 matrix, which is the most efficient way to perform the final transformation.

The one slightly annoying thing is that Spherefuns are all done as latitude/longitude grids, which means that to rotate them you need to do some trigonometric functions, then the 3x3 matrix–vector product, then some inverse trigonometric functions to go from latitude–longitude -> cartesian coordinates -> rotated coordinates -> back to latitude–longitude.

**Comment by ajt60gaibb** [comment]
I would like to have the improved `spherefun.rotate()` into spherefun before the next release. See branch `FastSphereTransform`, which contains a first iteration on a fast `spherefun.rotate()`.

**Comment by MikaelSlevinsky** [comment]
Can someone explain to me why this cannot be done in an order of operations proportional to the number of degrees of freedom? Maybe this is naive, breaks encapsulation, or is a MATLAB *faux pas*, but I suggest using Horner's rule on the coefficients of the row and/or column skeleton of the `spherefun`, depending on the Euler angle at play.

**Comment by ajt60gaibb** [comment]
Let `f` be a spherefun with trig degree `m` and `n` in the lat-long coordinate system and of rank `k`.  The NUFFT gives a `O(mnlog(mn))` algorithm, so not optimal in number of degrees of freedom. This is the same complexity as the online cost of SHT (without precomputation) using their relationship to SO3. 

I don't think we can do `O(k(m+n))` complexity, for at least two reasons: (1) The rank of the rotated spherefun is not necessarily related to the rank of the original spherefun (hence, `O(mn)` evaluation points seems necessary, so that's at least `O(mn)`), and (2) The tensor product grid after rotation is not a subset of a tensor grid in the original coordinate system. 

Did I understand your comment correctly?

**Comment by MikaelSlevinsky** [comment]
Yes, I'm sorry. It's more complicated than I thought. The NUFFT approach will be great!

**Comment by ajt60gaibb** [comment]
Rotating a function on the surface of the sphere is one of the classic applications of the SHT, with some remaining issues (see Greengard's publications). It just happens that with the double Fourier sphere method, one can avoid the SHT entirely.
