### ISSUE TITLE
Inconsistency in 'equi' flag between chebfun and chebfun2/chebfun3?

### ISSUE THREAD

**Issue by nickhale** [chebfun/chebfun#2052]
chebfun2 allows *adaptive* construction from equispaced data:
```
>> chebfun2(@(x,y) sin(x).*sin(y), 'equi')
ans =
   chebfun2 object
       domain                 rank       corner values
[  -1,   1] x [  -1,   1]        1     [0.71 -0.71 -0.71 0.71]
vertical scale = 0.71 
```
(as does chebfun3 - not shown), however chebfun does not:
```
>> chebfun(@(x) sin(x), 'equi')
Undefined operator '*' for input arguments of type 'function_handle'.
Error in smoothfun>funqui (line 122)
fvals = vals*linComb;
<snip>
```

To clarify chebfun *does* allow *fixed-length* construction from equispaced data:
```
>> chebfun(@(x) sin(x), 'equi', 10)
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       24     -0.84     0.84 
vertical scale = 0.84 
>> chebfun(sin(linspace(-1,1,10))', 'equi')
ans =
   chebfun column (1 smooth piece)
       interval       length     endpoint values  
[      -1,       1]       24     -0.84     0.84 
vertical scale = 0.84 
```

**Comment by aaustin141** [comment]
Actually, it seems that `chebfun2` and `chebfun3` just silently ignore the `'equi'` flag when doing an adaptive construction:
```
>> f = chebfun2(@(x, y) sin(x).*sin(y) + x.^2.*exp(sin(x + y)));
>> g = chebfun2(@(x, y) sin(x).*sin(y) + x.^2.*exp(sin(x + y)), 'equi');
>> f(0.1, 0.1)
ans =
   0.022164496639385
>> g(0.1, 0.1)
ans =
   0.022164496639385
```
Surely we'd see some tiny difference between the two computed values if the `'equi'` flag had any effect?  Similarly, we get the following from `chebfun3`:
```
>> f = chebfun3(@(x, y, z) sin(x).*sin(y).*sin(z) + z.*x.^2.*exp(sin(x + y)));
>> g = chebfun3(@(x, y, z) sin(x).*sin(y).*sin(z) + z.*x.^2.*exp(sin(x + y)), 'equi');
>> f(0.1, 0.1, 0.1)
ans =
   0.002214789375787
>> g(0.1, 0.1, 0.1)
ans =
   0.002214789375787
```

Looking briefly at `@chebfun2/constructor.m`, and `@chebfun3/constructor.m` I see that the `'equi'` flag gets parsed out but is only used when we call the files' respective `constructFromDouble()` subfunctions [here](https://github.com/chebfun/chebfun/blob/34f92d12ca51003f5c0033bbeb4ff57ac9c84e78/%40chebfun2/constructor.m#L62).  and [here](https://github.com/chebfun/chebfun/blob/34f92d12ca51003f5c0033bbeb4ff57ac9c84e78/%40chebfun3/constructor.m#L50).  Otherwise, the constrution proceeds as normal.

**Comment by trefethen** [comment]
I don't know what 'equi' would mean in an adaptive context.  If any of our codes are to implement some kind of adaptive 'equi', then their help texts should explain what this means -- but a discussion among Chebfunners would be appropriate first.

**Comment by nickhale** [comment]
Sorry, I wasn't thinking. I agree that adaptive construction from equally-spaced points make little sense.

However it would probably be a good idea to throw more sensible errors when a user attempts this (rather than the uninformative one from chebfun and silently ignoring it in chebfun2 and chebfun3).
