### ISSUE TITLE
very basic bug in ODE solution?!

### ISSUE THREAD

**Issue by trefethen** [chebfun/chebfun#2191]
It seem to me both numbers below should be 1, but the second one is -1.  Am I missing something?
```
>> L = chebop(0,1); L.lbc = 0;
>> L.op = @(y) diff(y)-1; y = L\0; y(1)
ans =  1
>> L.op = @(y) -diff(y)+1; y = L\0; y(1)
ans = -1
```

**Comment by aaustin141** [comment]
Looks like it's a bug in how `uminus()` gets handled somewhere.  (Inside `treeVar`?)  The following work fine for me:
```
>> L.op = @(y) -1*diff(y) + 1; y = L\0; y(1)
ans =
     1
>> L.op = @(y) 1 - diff(y); y = L\0; y(1)
ans =
     1
```
But this does not:
```
>> L.op = @(y) diff(-y) + 1; y = L\0; y(1)
ans =
    -1
```
Interestingly, this results in an error:
```
>> L.op = @(y) diff(-1*y) + 1; y = L\0; y(1)
Reference to non-existent field 'multCoeff'.
Error in treeVar/diff (line 259)
                'multCoeff', f.tree.multCoeff, ...
Error in chebop.vectorizeOp>@(y)diff(-1.*y)+1
Error in treeVar.toFirstOrder (line 56)
    fevalResult = funIn(args{:});
Error in chebop/solveivp (line 130)
        treeVar.toFirstOrder(N.op, rhs, N.domain);
Error in \ (line 49)
    [varargout{1:nargout}] = solveivp(N, rhs, pref, varargin{:});
```

**Comment by trefethen** [comment]
Remarkable.  Thanks, @aaustin141.  @asgeirbirkis, we'd be grateful if you'd take a look.

**Comment by asgeirbirkis** [comment]
Thanks @trefethen and @aaustin141 for raising this. I've now got some local changes that fixes the first four cases.

The `diff(-y)` and `diff(-1*y)` as reported by @aaustin141 requires some further consideration; the design of the `treeVar` class did not intend for these kind of expressions to be supported, as it requires differentiation of syntax trees for more complicated cases (e.g. diff(-exp(x)*u), cf. #2096). The scalar multiplication (and unary minus) can be made to work rather easily I believe, but the more complicated cases would require some more work. Perhaps for now, we could aim to support the scalar multiplication/uminus case, and throw an error for the more complicated ones?

(The `multCoeff` error is due to an obsolete property of the `treeVar` class, it's no longer thrown on my local branch.)
