### ISSUE TITLE
Can't run code from Exploring ODEs book

### ISSUE THREAD

**Issue by william-mitchell** [chebfun/chebfun#2251]
I've just tried to run three lines from page 116 of the ODE book.  This gives an error, as follows. 

>> clear all
>> N = chebop(0,30); N.lbc = [1; 0];
>> N.op = @(t,u,v) [diff(u)+v+u*(u^2+v^2); diff(v)-u+v*(u^2+v^2)]; 
>> [u,v] = N\0; plot([u v])

Error using treeVar.sortConditions (line 104)
The value of a derivative of a too high order was specified.

Error in chebop/solveivp (line 227)
    idx = treeVar.sortConditions(N.lbc, N.domain, diffOrders);

Error in  \  (line 49)
    [varargout{1:nargout}] = solveivp(N, rhs, pref, varargin{:});

**Comment by aaustin141** [comment]
I can reproduce this problem with the latest released version of Chebfun (v5.7.0), but it seems to have been fixed in f885d651, which will be included in the next release.  If you don't want to wait for the next release, you can download the development version of Chebfun [here](https://github.com/chebfun/chebfun/archive/development.zip).

**Comment by william-mitchell** [comment]
Thanks, that solved my question!
