### ISSUE TITLE
ODEs with Delta functions is not implemented in v5

### ISSUE THREAD

**Issue by gradywright** [chebfun/chebfun#670]
There does not appear to be any support for ODEs with Dirac-Delta functions on the RHS in v5.  This may be known issue, but I could not find it on the tracker.

**Comment by trefethen** [comment]
In writing _Exploring ODEs_, the loss of delta functions is a big problem/disappointment for me right now.  I wanted to demonstrate Green functions and I can't!  @mhsnjvd or @nickhale perhaps, am I right in suspecting that this is not an easy matter to implement?  An example of the kind of problem I wish I could solve is
```
L = chebop(-1,1);
L.lbc = 0; L.rbc = 0;
L.op = @(x,y) diff(y,2) + y;
x = chebfun('x');
f = dirac(x);
y = L\f;
plot(y)
```
but alas, at the moment this just gives y=0.  There's a Chebfun example `examples/ode-linear/DeltaODEs.m`, but it doesn't run in v5.

**Comment by nickhale** [comment]
I've just pushed something to [this branch](https://github.com/chebfun/chebfun/tree/feature-ode-deltas) that explores this. If I run your example I then get the following (which may or may not be correct, but at least is non-zero..)
![deltasoln](https://cloud.githubusercontent.com/assets/2035010/18471014/daf058a2-79af-11e6-84c8-697d3ae9a56d.png)

I don't have time to pursue this farther, but hopefully it will get someone on the right track. The major problem I foresee is that you really need to know the value of the (possibly non-constant) coefficient sitting in front of the highest derivative term in order to set the magnitude of the jump correctly. I also have no idea what should happen for systems of equations, and suggest we throw an error message there.
